### PR TITLE
Facebook Authentication with Two-Factor Authorization 

### LINKED ISSUE #103: [TODO] Support all OAuth providers
As an EmbedChat developer

**I need to**: Make sure that EmbeddedChat supports all OAuth providers

**So That**: There is no immediate limitations and everyone can access their RC instance without any data loss.

**Acceptance Criteria**

- [ ] Nextcloud OAuth
- [ ] Facebook OAuth
- [ ] Gitlab OAuth
- [ ] GitHub OAuth
- [ ] WordPress OAuth
- [x] Normal Input based sign-in (Username/Password) - highest priority

Docs: https://docs.rocket.chat/use-rocket.chat/rocket.chat-workspace-administration/settings/oauth

### **Sign in with Google should change with - "JOIN"**
image

### **Join should open up a modal with all the providers the user has given in props**
image

For Implementation, refer this PR: #12

### PR DESCRIPTION
**Pull request by VipinDevelops**
## Brief Title
Enhance User Security with Facebook Login and Two-Factor Authorization

## Description
This task is focused on enhancing the security measures of the Embed Chat App by integrating Facebook Authentication and Two-Factor Authorization. 

## Acceptance Criteria Fulfillment
 - [x] Integrate Facebook Authentication into the Embed Chat App
 - [x]  Implement Two-Factor Authorization for user accounts
 - [x]  Document the Facebook Authentication for Embed chat users 

Fixes #103  

Video/Screenshots

[Screencast from 2023-02-09 15-42-54.webm](https://user-images.githubusercontent.com/99081689/217790352-199c3c14-baac-4bce-bf6c-4eece462bbe6.webm)

### CODE REVIEW

**Comment by VipinDevelops** [comment]
Hey, @sidmohanty11 I have completed the development of this Facebook Auth feature and would like to request your review of the changes. If you have any questions or concerns, please don't hesitate to reach out to me.

Thank you for your time and consideration.

**Comment by VipinDevelops** [comment]
yeah you might think there is alot of line changes well i am also not sure of all the changes but they where added to the when i installed FB SDK here is a [link](https://github.com/RocketChat/EmbeddedChat/pull/127/commits/204b8ac0a4a7c7bdec7a2b332325f677e440a0f2) to that commit

**Comment by VipinDevelops** [comment]
I read little about this package.json lock thing and conclusion is i should push these have a look in this article https://dev.to/adamklein/package-lock-json-in-git-or-not-50l5

**Comment by VipinDevelops** [comment]
Hey @sidmohanty11 I removed the Facebook app secret from everywhere possible now it's only used once with all other props and to make a API call which is necessary other than that we don't  use it any where in the app

**Comment by sidmohanty11** [comment]
@VipinDevelops Thanks for the PR, but closing it as this is not be the approach we want to proceed with (as discussed).

**Pull request closed without merging**
