### PR TITLE
Styled scrollbar for messagelist

### LINKED ISSUE #284: Style the scrollbar for message list.
The default scrollbar in the message list panel currently maintains the browser's default style. It is functional but doesn't align with the application's overall aesthetic. Implementing a custom style for the scrollbar will enhance the visual appeal and user experience, making the UI more consistent and engaging.

###### Expected Scrolbar Design
Expected Scrollbar design

### PR DESCRIPTION
**Pull request by Yashraj7890**
#Styled scrollbar for message list 
Made use of webkit-scrollbar to style the scrollbar, these changes will successfully change the scrollbar on all webkit-based browsers (e.g., Chrome, Edge, Opera, Safari, all browsers on iOS).
## Video/Screenshots
Appearance after changes on MS Edge:

Screenshot (10)

Appearance after changes on Google Chrome:

Screenshot (11)

Fixes #284

### CODE REVIEW

**Comment by abhinavkrin** [comment]
Hey @Yashraj7890 , Thanks for the PR. This is awesome. Could you also check why the horizontal scrollbar is present?

**Comment by Yashraj7890** [comment]
> Hey @Yashraj7890 , Thanks for the PR. This is awesome. Could you also check why the horizontal scrollbar is present?

The horizontal scrollbar will only appear only if the device width is too small (like really small), I mean it's sort of necessary to have to there to scroll through the messages horizontally when screen width is too small. Actually, I was just designing the vertical scrollbar but then I checked the page for responsiveness it was completely responsive, and a horizontal scrollbar appears when the width turns too small, so I ended up styling it too.

This video shows the behavior of the scrollbar :-


https://github.com/RocketChat/EmbeddedChat/assets/98230836/5b39d948-9d5a-4aaa-8cab-9ef3e8af7065

**Comment by abhinavkrin** [comment]
Hey @Yashraj7890 Thanks for the clarification. I think your solution works fine for the issue.

**Review by abhinavkrin — APPROVED** [review]
Thanks @Yashraj7890 LGTM!

**Pull request merged**
