### PR TITLE
Refactor sidebar components

### LINKED ISSUE #504: Refactor menu components
As an EmbeddedChat developer

**I need to**:
Refactor the menu components.

Currently, each menu below has an individual store, component, and css module:
1. Room information
2. Members
4. Threads
5. Search
6. Mentions
7. Pinned messages
8. Starred messages

Most of the code are repeated and can be refactored into a general menu framework. 

**So That**:
We...
1. Improve UI consistency
2. Enhance maintainability of existing menus
3. Bring easier enhancement with future menu features and better scalability with new menus

**Acceptance Criteria**

- [ ] All current menus share a general component, CSS module, and store.
- [ ] The menus behave the same as before
- [ ] The refactored menu framework have flexibility for all types of menus

### PR DESCRIPTION
**Pull request by JeffreytheCoder**
# Brief Title

## Acceptance Criteria fulfillment

- [x] All current menus share a general component and CSS module
- [x] The menus behave the same as before
- [x] The refactored menu framework have flexibility for all types of menus

Fixes #504

## Video/Screenshots
All menus look the same as before

### CODE REVIEW

**Comment by JeffreytheCoder** [comment]
Anyone knows why the lint check workflow fails with the following error?

```
>  Lerna (powered by Nx)   Running target format:check for 6 projects failed

   Tasks not run because their dependencies failed or --nx-bail=true:
   
   - e2e-react:format:check
   - @embeddedchat/htmlembed:format:check
   
   Failed tasks:
   
   - @embeddedchat/react:format:check
   ```

**Comment by Spiral-Memory** [comment]
@JeffreytheCoder , I suggest attaching a video showcasing everything working smoothly (all sidebar components) without any rendering issue or console errors for every functionality in the app. I can see that you have only extracted the very common elements and passed the other part as a children prop. While it's not extremely modular, which is good as it reduces the chances of introducing bugs, as discussed earlier there is still potential for issues and since **we have a plan to release it as next major version soon**. Therefore, please ensure from your side as well, and including a video with no console errors will be helpful.

**Comment by JeffreytheCoder** [comment]
@Spiral-Memory Thanks bro! It's hard to modularize sidebar content because they vary a lot, but having a modularized sidebar wrapper solves some inconsistent stylings, and it's better to maintain and add upcoming features like resizing along with the chat window. 

Here's the recording below that shows all sidebars work as before, with no console warning or error:
sidebar-after

I'll create another PR to put pinned & starred messages into the general sidebar after #501 is reviewed.

**Comment by Spiral-Memory** [comment]
> @Spiral-Memory Thanks bro! It's hard to modularize sidebar content because they vary a lot, but having a modularized sidebar wrapper solves some inconsistent stylings, and it's better to maintain and add upcoming features like resizing along with the chat window.
> 
> Here's the recording below that shows all sidebars work as before, with no console warning or error: sidebar-after [ sidebar-after ](https://private-user-images.githubusercontent.com/35394596/311847777-0a7c50d5-8d98-4667-90c2-5d68d7957298.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxODcxNDEsIm5iZiI6MTcxMDE4Njg0MSwicGF0aCI6Ii8zNTM5NDU5Ni8zMTE4NDc3NzctMGE3YzUwZDUtOGQ5OC00NjY3LTkwYzItNWQ2OGQ3OTU3Mjk4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE5NTQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNmJjZmM2YjU3ZjZjNDg2NzM1YzQ5OGZlMjZmNTVmMDI3ZTVmM2JiNTZkYjNjNGUyODEzODE0ZTMwMWQ5MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fb8Km7LUBbaOSqzJj0pAbD2zYrDXbpE4XPGGpCp6Mag) [ ](https://private-user-images.githubusercontent.com/35394596/311847777-0a7c50d5-8d98-4667-90c2-5d68d7957298.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxODcxNDEsIm5iZiI6MTcxMDE4Njg0MSwicGF0aCI6Ii8zNTM5NDU5Ni8zMTE4NDc3NzctMGE3YzUwZDUtOGQ5OC00NjY3LTkwYzItNWQ2OGQ3OTU3Mjk4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE5NTQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNmJjZmM2YjU3ZjZjNDg2NzM1YzQ5OGZlMjZmNTVmMDI3ZTVmM2JiNTZkYjNjNGUyODEzODE0ZTMwMWQ5MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fb8Km7LUBbaOSqzJj0pAbD2zYrDXbpE4XPGGpCp6Mag)
> 
> I'll create another PR to put pinned & starred messages into the general sidebar after #501 is reviewed.

Yep i told you, it has so much variation and hard to modularize hehe ! Anyway great work !

**Comment by JeffreytheCoder** [comment]
Yes it works :)

many-threads

**Comment by Spiral-Memory** [comment]
Awesome 🥳🥳

**Comment by JeffreytheCoder** [comment]
@sidmohanty11 Ready for review

**Review by sidmohanty11 — COMMENTED** [review]
@JeffreytheCoder awesome! Had one question, how does it look in minimised mode?

**Review by sidmohanty11 — APPROVED** [review]
Thanks @JeffreytheCoder !!

**Pull request merged**
