### PR TITLE
Feat: Added Scroll-to-Message Functionality

### PR DESCRIPTION
**Pull request by abirc8010**
# Brief Title

This pull request introduces a feature that allows users to scroll to a specific message in the message list when clicked on a message in the sidebar (in Threads , Mentions, Starred Messages, Pinned Messages and Search Messages ).

## Acceptance Criteria fulfillment

- [ ] Introduced a `setJumpToMessage` function inside the MessageAggregator component

- [ ] Added an onClick event handler to the arrow-back icon that calls `setJumpToMessage(msg._id) ` when the icon is clicked. 

- [ ]  the function `setJumpToMessage` searches for the message element using its ID (`ec-message-body-${msgId}`) and uses scrollIntoView() to smoothly scroll to the message. 

## Video/Screenshots

[jump_to_message.webm](https://github.com/user-attachments/assets/3e4da7b7-2e73-49ea-afd2-7f2d85d97752)

## PR Test Details

**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-667 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

### CODE REVIEW

**Comment by abirc8010** [comment]
Hey @Spiral-Memory ,  
I’ve implemented a feature that allows the user to be taken directly to the specific message in the message list when they click on the message body.
Is it ok?

**Comment by Spiral-Memory** [comment]
Yep, looks fine but for every message, you are maintaining a ref, not sure about it's performance impact when thousands of messages are present in the channel.. will have to discuss with other collaborators to integrate this.

**Comment by abirc8010** [comment]
> Yep, looks fine but for every message, you are maintaining a ref, not sure about it's performance impact when thousands of messages are present in the channel.. will have to discuss with other collaborators to integrate this.

I have changed my approach and updated my PR description.

In this approach we don't need to maintain ref , instead we update the URL as implemented in RC

**Comment by abirc8010** [comment]
@Spiral-Memory will this new approach be better ?

**Comment by abirc8010** [comment]
Hey @Spiral-Memory,
I fixed an alignment issue with the scroll-to-message icon in popup mode in my latest commit. You can review and approve the changes to see them reflected in the deployment.

**Review by Spiral-Memory — APPROVED** [review]

**Comment by Spiral-Memory** [comment]
Awesome work @abirc8010 
Happy contributing..

**Pull request merged**
