### PR TITLE
fix: Room information display problem

### LINKED ISSUE #340: Room Information not displayed
### Description:

Room Information not displayed when Room-Information menu option is clicked.

### Steps to reproduce:

1. Click on three dot menu.
2. Click on Room - Information
3. Information not displayed.

### Expected behavior:
Room Information should be displayed.

### Actual behavior:
roomInfo

### PR DESCRIPTION
**Pull request by shivang-16**
### Description
Fixed the room information problem 

## Video/Screenshots
Screenshot 2024-01-31 at 12 22 00 AM

### CODE REVIEW

**Comment by Spiral-Memory** [comment]
Hey, @shivang-16 , the issue with this channel info occurs when the user refreshes the page. This is related to the sequence of fetching channel info and user authentication. I have already created a pull request (PR) at https://github.com/RocketChat/EmbeddedChat/pull/427 to address this issue. Adding another useEffect in channelInfo.js is not necessary, as it is already implemented in chatHeader.js.

I also kindly request you to check if a similar PR has already been submitted. If one exists, please avoid creating a duplicate PR. Additionally, when someone is actively working on an issue, it's essential to confirm with the maintainers before taking it on to avoid wasting others' efforts.

**Comment by Spiral-Memory** [comment]
Hey, @shivang-16  , the issue with this channel info occurs when the user refreshes the page. This is related to the sequence of fetching channel info and user authentication, the similar issue also happens with keeping setting intact over refresh and at many places. I have already created a pull request (PR) at https://github.com/RocketChat/EmbeddedChat/pull/427 to address this issue. Adding another useEffect in RoomInformation.js is not necessary, as it is already implemented in chatHeader.js.

I also kindly request you to check if a similar PR has already been submitted. If one exists, please avoid creating a duplicate PR. Additionally, when someone is actively working on an issue, it's essential to confirm with the maintainers before taking it on to avoid wasting others' efforts.

**Comment by shivang-16** [comment]
I initially searched for it, I found an open issue #340..so I started working on it...I am closing this PR since you have already created a PR.

**Comment by Spiral-Memory** [comment]
Sure @shivang-16 , Thanks

**Pull request closed without merging**
