### PR TITLE
fix: infinite render and console errors due to search component

### LINKED ISSUE #502: [BUG] Infinite render of search message component
### Description:

There is an issue of infinite rendering when the search component is mounted.

### Steps to reproduce:

1. Set up Embedded Chat.
2. Open the Console window.
3. Open the Search Message Sidebar.

### Expected behavior:

The component should be rendered when required.

### Actual behavior:

The component is re-rendering infinitely when the text message is empty, also there is an issue with size attribute of Icon.

https://github.com/RocketChat/EmbeddedChat/assets/78961432/5d3f3f4c-a193-4331-9317-9317abb777a9

### PR DESCRIPTION
**Pull request by Spiral-Memory**
# Brief Title
I have observed some minor bugs introduced by PR #497 , and this PR is intended to address these issues of infinite renders and console errors as quickly as possible

## Acceptance Criteria Fulfillment

- [x] Resolved infinite renders
- [x] Resolved console error related to SVG size

Fixes #502

## Video/Screenshots

https://github.com/RocketChat/EmbeddedChat/assets/78961432/9430f9e8-cc01-4396-8f12-90bd17e51e2b

### CODE REVIEW

**Comment by Spiral-Memory** [comment]
Hey @sidmohanty11 , there is a minor bug introduced after recent merge #497 while rendering the search component. It was rendering infinitely. I have tried fixing it. Please review this as early as possible.

**Comment by JeffreytheCoder** [comment]
@Spiral-Memory Thanks for spotting this 👍

**Comment by Spiral-Memory** [comment]
> @Spiral-Memory Thanks for spotting this 👍

No worries, bro 😃! We are here to help each other.

**Review by sidmohanty11 — APPROVED** [review]
Thanks a lot @Spiral-Memory good catch!

**Pull request merged**
