### PR TITLE
[Fix/#457]: Invite link appearance fixed/Copy to clipboard button added/Improvements in the slash command panel UI/Bug-fixes

### PR DESCRIPTION
**Pull request by umangutkarsh**
# Brief Title

This PR fixes ** Bug1 + Bug2 + Feature1** of issue: #457 

## Acceptance Criteria fulfillment

- [X] The invite link (for channel) button should not appear if the logged in user is not an admin.
- [X] A copy to clipboard button (for invite link) can be added to improve UX.
- [X] Pressing the enter key doesn't send the message with slash command.
- [X] Improve slash command panel
- [X] Unexpected error occurs when the invite link is selected and dragged.
- [X] Linting Errors fixed.

Addresses #457 

## Video/Screenshots
[inv-issue.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/8440e0ba-7409-4055-a68b-338e5c2892e4)

[slash-c.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/b17acbae-9f90-40e7-a886-a5b75f2f38e7)

### CODE REVIEW

**Comment by umangutkarsh** [comment]
Hey @abhinavkrin , @sidmohanty11 . Please review this. Fixed some bugs, and added a minor feature.

Thanks

**Comment by umangutkarsh** [comment]
> LGTM! I had one question, should the invite link redirect the user to RC or the user's webpage where EC is embedded

I have not really tried embedding EC on some other webpage. I usually use the docker image of RC and the link redirects to the RC.

**Comment by umangutkarsh** [comment]
Hey @sidmohanty11 @abhinavkrin can you review this PR?

**Comment by umangutkarsh** [comment]
> Hey @sidmohanty11 @abhinavkrin can you please review this PR?
> 
> Thanks

Hi @sidmohanty11 can you please review this? Thanks

**Review by sidmohanty11 — APPROVED** [review]

**Pull request merged**
