### PR TITLE
Resolve merge conflicts

### LINKED ISSUE #414: New Message notification.
As an EmbeddedChat developer

**I need to**: Integrate a feature of showing a notification popup when a new message is sent by some one else on the chat and the current user has scrolled up the chat-box

**So That**: By clicking the popup, the current user can get to the new-message instead of manually scrolling down.

**Acceptance Criteria**

- [ ] Integrate a notification popup (just like in Rocket-Chat).

### Screenshots/ScreenRecord:

Like shown in the screen-record.

[newmsg.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/5f7ae1ec-b167-43c1-805b-5bdffd29f0b3)

### PR DESCRIPTION
**Pull request by umangutkarsh**
# Brief Title
This PR is made to resolve some merge conflicts in PR #445 

## Acceptance Criteria fulfillment

- [X] Add missing prop

Fixes #414

### CODE REVIEW

**Comment by umangutkarsh** [comment]
Hi @abhinavkrin . 
After reviewing the PRs and recent merges again, I realized there were some conflicts which affected the PR #445 .
Will resolve if I find some other conflicts.


Will let you know after resolving them.
Thanks.

**Comment by Spiral-Memory** [comment]
Great @umangutkarsh , I also noticed this issues and thought of fixing the issues. Its great to see that you resolved the conflicts.

**Comment by Spiral-Memory** [comment]
There are one more issue with this as well, I will record, apart from passing the props, I will record a video and send you. It would be great if you will fix that too.

**Comment by Spiral-Memory** [comment]
When the chat body is in minimized mode, the button feels as if it is cut off. Could you please look into this as well? Additionally, yesterday, besides the scrollToBottom error, I also noticed an error related to scrollToTop in the console. I'm not sure if it is connected to this issue, so I would suggest you take another look to fix any such issues.

Screenshot from 2024-02-08 15-06-04

**Comment by Yashraj7890** [comment]
There is another issue here @umangutkarsh , the new messages notification is also triggered when any message is pinned or starred which is unnecessary .

**Comment by Spiral-Memory** [comment]
@umangutkarsh, You can close this PR. While solving linting issue, i have added the scrollToBottom error as it was showing issues.

However you can implement the suggestions by me and yashraj if you want.

Thanks

**Comment by umangutkarsh** [comment]
> There is another issue here @umangutkarsh , the new messages notification is also triggered when any message is pinned or starred which is unnecessary .

Thanks @Yashraj7890 for pointing this out. Will start working on this soon.

**Comment by umangutkarsh** [comment]
> @umangutkarsh, You can close this PR. While solving linting issue, i have added the scrollToBottom error as it was showing issues.
> 
> However you can implement the suggestions by me and yashraj if you want.
> 
> Thanks

Sure.

**Review by abhinavkrin — COMMENTED** [review]
Hey @umangutkarsh is this required?

**Comment by umangutkarsh** [comment]
> Hey @umangutkarsh is this required?

Hi @abhinavkrin . I'll look into this to resolve any bugs . Will let you know soon.

**Pull request closed without merging**
