### PR TITLE
Aligned JOIN Button

### LINKED ISSUE #269: Misalignment of 'JOIN' Button
### Description:
The 'JOIN' button is not properly aligned (vertically) with the rest of the elements in the chat interface.
join-button-not-aligned

### Steps to reproduce:
You need to be logged out to see join buttton

### PR DESCRIPTION
**Pull request by Kamlesh72**
Fixes #269

- Fixed Alignment of 'JOIN' Button.

Fixed JOIN Button Alignment

### CODE REVIEW

**Review by abhinavkrin — CHANGES_REQUESTED** [review]
Can you remove `.DS_Store` from the commit?

**Comment by Kamlesh72** [comment]
> Can you remove `.DS_Store` from the commit?

All 3 .DS_Store ?

**Comment by abhinavkrin** [comment]
Yes. I think these are not related to the project. https://www.google.com/search?q=.ds_store

**Review by abhinavkrin — APPROVED** [review]
LGTM!

**Pull request merged**
