### PR TITLE
Add more markdown styles

### LINKED ISSUE #121: Add more markdown styles
As an EmbedChat developer

**I need to**: Have following markdown rules for HEADING, UNORDERED_LIST, ORDERED_LIST, TASKS, QUOTE, LINE_BREAK, Link, Color etc.

**So That**: All kinds of message are displayed in appropriate formatted way

**Acceptance Criteria**

- [ ] Heading
- [ ] Unordered list
- [ ] Ordered list
- [ ] Tasks
- [ ] Quote
- [ ] Reaction emoji
- [ ] Color
- [ ] Line Break

**Expected behaviour**
image

**Actual behaviour**
image

### PR DESCRIPTION
**Pull request by imf-ali**
As an EmbedChat developer

**I need to**: Have following markdown rules for HEADING, UNORDERED_LIST, ORDERED_LIST, TASKS, QUOTE, LINE_BREAK, Link, Color etc.

**So That**: All kinds of message are displayed in appropriate formatted way

**Acceptance Criteria**

- [x] Heading
- [x] Unordered list
- [x] Ordered list
- [x] Tasks
- [x] Quote
- [x] Reaction emoji
- [x] Color
- [x] Line Break

**Expected behaviour**
image

**Behaviour so far**
image

Fix #121

### CODE REVIEW

**Comment by imf-ali** [comment]
image

**Comment by imf-ali** [comment]
Hey @sidmohanty11, can you please review this?

**Comment by imfAli** [comment]
Link part and mention user is being taken up by other guys I think.

**Comment by imf-ali** [comment]
Link part and Mention user is being taken up by someone else I think.

**Review by sidmohanty11 — CHANGES_REQUESTED** [review]
Thanks @imf-ali. 

Does fuselage message components have that much spacing between messages?

**Comment by imf-ali** [comment]
> Thanks @imf-ali.
> 
> Does fuselage message components have that much spacing between messages?

yes, I needed to discuss this. Somehow there is 12px of padding space to the top and bottom of every message div which is causing this. I will mention this in channel if someone can help.

**Comment by sidmohanty11** [comment]
@imf-ali yup please

**Comment by KoushikAD1234** [comment]
Hey @sidmohanty11 and @imf-ali Can I collaborate and fix this issue?

**Comment by imf-ali** [comment]
Hey @KoushikAD1234, @SKB231  seem to have fixed the extra padding part as discussed in channel, we still have got some styling fix to do. Currently the thing is, in embedded chat we still have got extra spacing around the message div even after fixing the extra padding part. Below screenshot you can see the difference, this extra spacing is coming from the Message fuselage component. You may go ahead on this if you like, u may contribute in the same PR or communicate with @sidmohanty11 and create a different PR.

image

image

**Comment by KoushikAD1234** [comment]
@imf-ali cool, I will look into it.

**Comment by sidmohanty11** [comment]
@imf-ali Thanks! We can create a separate PR for that! Let's merge this. Please take a look at the merge conflicts

**Review by sidmohanty11 — APPROVED** [review]

**Pull request merged**
