### PR TITLE
Fix/#389 enhance drop box

### LINKED ISSUE #389: Enhance Attachment drag drop feature.
As an EmbeddedChat developer

**I need to**: Enhance the features of drag and drop attachment functionality.

**So That**: It provides a better UI and UX to the users and resolve some bugs.

**Acceptance Criteria**

- [x] Improve UI UX of `AttachmentWindow.js`
- [x] Improve Backdrop of `AttachmentWindow,js` and resolve some bugs
- [x] Enhance the drag and drop box to attach files to cover the entire message-box

**Below Issues are attached as a screen-record**:

[attachm.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/0ef159e4-d965-4439-8c0f-c385807c91cd)

### PR DESCRIPTION
**Pull request by umangutkarsh**
# Brief Title
This PR fixes #389 .
Below are the issues fixed.

## Acceptance Criteria fulfillment

- [X] Improve UI UX of AttachmentWindow.js
- [X]  Improve Backdrop of AttachmentWindow.js and resolve some bugs
- [X] Enhance the drag and drop box for attaching files, to cover the entire message-box

Fixes #389 

## Video/Screenshots

[drop-box.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/b1572567-e125-4a28-a259-3aa4695ad1d5)

### CODE REVIEW

**Comment by umangutkarsh** [comment]
Please review the PR, and let me know if anything else is required, or anything needs to be fixed.

**Comment by umangutkarsh** [comment]
Hi, I have to make some changes to this code. Once I push those changes, only then review this. 
Will comment when I push them.
Thanks

**Comment by umangutkarsh** [comment]
Hi @abhinavkrin @sidmohanty11 . I've pushed the changes. Please review it and let me know if anything else is required.
Thanks.

[dropf.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/c176e4af-c556-4c06-ac05-6ee20f212a5a)

**Review by abhinavkrin — CHANGES_REQUESTED** [review]
Hey @umangutkarsh , Thanks for the fix. Could you create a component that would include all the handler and other code related to drop box. So that the EmbeddedChat component is clean.
So that by including the component say '<DropBoxProvider />' in EmbeddedChat, the drop box functionality is taken care of.

**Comment by umangutkarsh** [comment]
> > Hey @umangutkarsh , Thanks for the fix. Could you create a component that would include all the handler and other code related to drop box. So that the EmbeddedChat component is clean.
> > So that by including the component say '<DropBoxProvider />' in EmbeddedChat, the drop box functionality is taken care of.
> 
> Hi @abhinavkrin . Sure, will work on it and will let you know.
> Thanks

Hi @abhinavkrin . I'm having some trouble using wsl extension on vscode. Might take some time. Thanks.

**Comment by umangutkarsh** [comment]
> Hey @umangutkarsh , Thanks for the fix. Could you create a component that would include all the handler and other code related to drop box. So that the EmbeddedChat component is clean. So that by including the component say '' in EmbeddedChat, the drop box functionality is taken care of.

Hi @abhinavkrin . I am not able to figure out the component where EmbeddedChat is rendered, so that I can wrap the Embedded-Chat component in <DropBoxProvider> to access the DropBoxContext.

This is the approach I have followed:

```
import { createContext } from 'react';

const DropBoxContext = createContext();

export default DropBoxContext;
```
create a context^

```
import React, { useEffect, useState } from 'react';
import useAttachmentWindowStore from '../../store/attachmentwindow';
import PropTypes from 'prop-types';
import DropBoxContext from '../../context/DropBoxContext';



const DropBoxProvider = ({ children }) => {

   const data = useAttachmentWindowStore((state) => state.data);
   const setData = useAttachmentWindowStore((state) => state.setData);
   const toggle = useAttachmentWindowStore((state) => state.toggle);

   const [onDrag, setOnDrag] = useState(false);
   const [leaveCount, setLeaveCount] = useState(0);

   const handleDrag = (e) => {
      e.preventDefault();
   };

   const handleDragEnter = () => {
      setOnDrag(true);
   };

   const handleDragLeave = () => {
      if ((leaveCount % 2) === 1) {
         setOnDrag(false);
         setLeaveCount(leaveCount + 1);
      } else {
         setLeaveCount(leaveCount + 1);
      }
   };

   const handleDragDrop = (e) => {
      e.preventDefault();
      setOnDrag(false);
      setLeaveCount(0);

      toggle();
      setData(e.dataTransfer.files[0]);
   };

   useEffect(() => {
      document.addEventListener('dragover', handleDrag);
      document.addEventListener('drop', handleDragDrop);
      return () => {
         document.removeEventListener('dragover', handleDrag);
         document.removeEventListener('drop', handleDragDrop);
      };
   }, []);



   return (
      <DropBoxContext.Provider value={{
         onDrag,
         data,
         setData,
         handleDrag,
         handleDragEnter,
         handleDragLeave,
         handleDragDrop
      }}>
         {children}
      </DropBoxContext.Provider>
   );
};

DropBoxProvider.propTypes = {
   children: PropTypes.node.isRequired,
};

// export const useDropBox = () => {
//    return useContext(DropBoxContext);
// };

export default DropBoxProvider;

```
create a Provider to access the methods and states in other files.

```
import { useContext } from 'react';
import DropBoxContext from '../context/DropBoxContext';

export const useDropBox = () => {
   return useContext(DropBoxContext);
};
```

create a custom hook to access the context.


```
const { onDrag, data, handleDrag, handleDragEnter, handleDragLeave, handleDragDrop } = useDropBox();
```
using this hook in EmbeddedChat.js to access the states, and methods defined in the context.

But I'm getting this error:
errs

**Comment by umangutkarsh** [comment]
Hi @abhinavkrin . Please review the changes. I have created a custom hook to access the methods and states required for the DropBox. Also created a DropBoxOverlay component.

Thanks.

**Comment by abhinavkrin** [comment]
Hey @umangutkarsh Thanks for the PR. This looks cool. Could you resolve the merge conflicts?

**Comment by umangutkarsh** [comment]
> Hey @umangutkarsh Thanks for the PR. This looks cool. Could you resolve the merge conflicts?

Hey @abhinavkrin . I've resolved the merge conflicts.
Thanks

**Comment by abhinavkrin** [comment]
Hey @Spiral-Memory I have a feeling that recent merges might affect this PR. Could you review this PR once?

**Comment by Spiral-Memory** [comment]
> Hey @Spiral-Memory I have a feeling that recent merges might affect this PR. Could you review this PR once?

Yes Sure

**Comment by abhinavkrin** [comment]
> @abhinavkrin , In which file do you think there might be issues with recent merges ?

Just review the overall PR.

**Comment by Spiral-Memory** [comment]
> > @abhinavkrin , In which file do you think there might be issues with recent merges ?
> 
> Just review the overall PR.

Hey the overall PR looks fine to me, In earlier PRs, there was no much changes at these locations, I feel.

**Comment by Spiral-Memory** [comment]
@abhinavkrin , If you want to be on safe side, Me and @umangutkarsh will test the changes on the local machine for a day and let you know.

**Comment by Spiral-Memory** [comment]
Hey @abhinavkrin , I tested his branch also, everything is looking good to me. 

Just a small suggestion to @umangutkarsh , remove the x-scroll from here (happens when you try to upload a long height image)
image

**Comment by umangutkarsh** [comment]
> Hey @abhinavkrin , I tested his branch also, everything is looking good to me.
> 
> Just a small suggestion to @umangutkarsh , remove the x-scroll from here and shrink things a little more (happens when you try to upload a long height image) image

@Spiral-Memory . The horizontal scroll was not appearing on my screen. 
Anyways I have shrunk things a little bit.

> Hey @abhinavkrin , I tested his branch also, everything is looking good to me.
> 
> Just a small suggestion to @umangutkarsh , remove the x-scroll from here and shrink things a little more (happens when you try to upload a long height image) image

@Spiral-Memory the horizontal - scroll was not appearing on my screen.
Anyways I've shrunk things up a little bit.

**Comment by Spiral-Memory** [comment]
@umangutkarsh, Okay got it !. The reason might be due to different screen sizes or zoom value, I will suggest you to disable the x-scroll to none

**Comment by umangutkarsh** [comment]
> @umangutkarsh, Okay got it !. The reason might be due to different screen sizes or zoom value, I will suggest you to set the x-scroll to none

Okayy @Spiral-Memory !

**Review by Spiral-Memory — APPROVED** [review]

**Review by abhinavkrin — APPROVED** [review]

**Pull request merged**
