### PR TITLE
Starred Model fix

### LINKED ISSUE #627: Starred Message in thread not visible in the Starred Message Model
### Description:

Starred message in thread is not visible in the Starred Message Model.

### Steps to reproduce:

1. Go to thread
2. Starred the Message
3. Open the starred message model from the top right view (from the dropdown)
4.  Starred message in the thread will not be visible in the model

### Expected behavior:

Starred message in thread should be visible in the Starred Message Model.

### Actual behavior:
https://github.com/user-attachments/assets/9f2c487d-fc4a-496f-bcfb-195007c56054

### PR DESCRIPTION
**Pull request by smritidoneria**
# Brief Title

Starred Message in thread is shown in starred Modal as well.

## Acceptance Criteria fulfillment

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

Fixes #627

## Video/Screenshots

https://github.com/user-attachments/assets/c4288356-0bab-485e-a5d9-d07f55adedf8

### CODE REVIEW

**Review by Spiral-Memory — APPROVED** [review]

**Comment by Spiral-Memory** [comment]
Looks good to me ! 

Thanks for the fix @smritidoneria

**Comment by Spiral-Memory** [comment]
Hey @smritidoneria 
Could you please run prettier ?

**Comment by smritidoneria** [comment]
> Hey @smritidoneria Could you please run prettier ?

done

**Comment by Spiral-Memory** [comment]
Thanks for the contribution @smritidoneria

**Pull request merged**
