### PR TITLE
Feat: add edit room information feature

### LINKED ISSUE #731: feat: Add room information edit feature
As an EmbeddedChat developer

**I need to**:
Add room information edit feature (like editing room name , avatar , topic, announcement , etc) similar to RC.

**So That**:
users with edit permission can edit the informations directly from embeddedChat.

**Acceptance Criteria**

[Screencast from 2024-12-25 14-23-07.webm](https://github.com/user-attachments/assets/cee381d0-25e6-4ccb-9f84-53136eaac11d)

- [ ] Add Room information edit option
- [ ] Add a Modal to display announcement
- [ ] Real time changes to be reflected to every users

### PR DESCRIPTION
**Pull request by abirc8010**
# Brief Title
Allow users with edit permissions to edit room information

## Acceptance Criteria fulfillment

- [ ] Add functionality to edit room name, description, topic, and announcement.
- [ ] Implement a modal to display the announcement.
- [ ] Ensure edit option is only visible to users with edit permission

Fixes #731 

## Video/Screenshots
[Screencast from 2024-12-25 14-54-06.webm](https://github.com/user-attachments/assets/732d7c1f-f9bf-46ea-b9d7-c8b2a8132caa)

## PR Test Details

**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-732 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

### CODE REVIEW

**Comment by Spiral-Memory** [comment]
Hi @abirc8010 ,

I’m really sorry to say, but this isn’t the intended purpose of EmbeddedChat.

Editing room information and similar actions are not necessary here, as these will be managed remotely by the RC admin. I may have to close this PR, I don't really want anyone's efforts to be wasted, so if you are working on an issue which you are confused about, maybe pls confirm with me or the other maintainers before starting to work on it. 

However, I do like the announcement feature! Is it available in Rocket.Chat as well? If yes, please raise a separate PR for it with an improved UI. The current UI for attachments doesn’t look very good.

**Comment by abirc8010** [comment]
Hey @Spiral-Memory , I drew inspiration for the announcement UI from RC. I'd really appreciate your feedback and suggestions on how to enhance it for EC.

[Screencast from 2024-12-25 14-23-07.webm](https://github.com/user-attachments/assets/8eedf5a6-c39f-499e-a1e9-4e06a037b152)

**Comment by Spiral-Memory** [comment]
Switch to light mode in RC and show me how it looks

**Comment by abirc8010** [comment]
image

**Comment by Spiral-Memory** [comment]
Alright, try to match the primary colors (don't use any hardcoded colors, you can take help of lighten, darken function in ec to adjust) in EC with the header. Make sure it works well in both light / dark modes and in all prebuilt themes. 

Reduce the padding slightly, and don't open the modal on click. Only open the modal when the announcement message doesn't fit in the header (ensure to use an ellipsis style to truncate the extra text).

Also, ensure that a prop can be passed as false to EmbeddedChat to hide the announcement header if required.

**Pull request closed without merging**
