### PR TITLE
feat: Implemented search member and display member info feature

### LINKED ISSUE #707: Feat: Include 'search member' and 'display member info' feature
As an EmbeddedChat developer

**I need to**:

Implement a search and display member info feature that allows searching members and showing detailed information on clicking a particular member.

**So That**:

Users can easily find and view details of specific members.

**Acceptance Criteria**

- [ ] Add a Search box in the 'members' section
- [ ] filter the members based on username or name attribute
- [ ] Clicking on a user must display user info

### PR DESCRIPTION
**Pull request by abirc8010**
# Brief Title
 Implemented a search and display member info feature that allows searching members and showing detailed information on clicking a particular member.

## Acceptance Criteria fulfillment

- [ ] Included a search box in the 'Members' section. 
- [ ] The search updates the member list dynamically as the user types using `members.filter` based on `username` and `name` attribute
- [ ] Utilized `useSetExclusiveState` and `useUserStore` to display the userInfo by attaching an onClick event inside `RoomMemberItem`

Fixes #707 

## Video/Screenshots
[Screencast from 2024-12-21 22-15-54.webm](https://github.com/user-attachments/assets/fe3b89a3-e4b2-4e96-97ca-c76ebbf858d0)

**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-708 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

### CODE REVIEW

**Review by Spiral-Memory — APPROVED** [review]
LGTM

**Comment by Spiral-Memory** [comment]
Hi @abirc8010 

Looks good to me. Great work!  

However, the width of the user info side panel is not the same as the others. Could you please fix that in this PR? Also, please add the required padding to the other side panels, as I mentioned in the last merged PR.

**Review by Spiral-Memory — APPROVED** [review]

**Comment by Spiral-Memory** [comment]
Let me know once you fix both

**Comment by abirc8010** [comment]
Hey @Spiral-Memory I have fixed the issues.

**Review by Spiral-Memory — APPROVED** [review]

**Comment by Spiral-Memory** [comment]
Great work @abirc8010

**Pull request merged**
