### PR TITLE
Linting setup

### LINKED ISSUE #32: Setup Linting
As an EmbedChat developer

**I need to**: setup linting

**So That**: my code is clean and readable

**Acceptance Criteria**

- [ ] make use of industry-standard linting (airbnb)

### PR DESCRIPTION
**Pull request by imf-ali**
# Setup Linting

As an EmbedChat developer

I need to: setup linting

So That: my code is clean and readable

## Acceptance Criteria fulfillment

- [x] make use of industry-standard linting (airbnb)

Fixes #32

### CODE REVIEW

**Comment by imf-ali** [comment]
Hi @sidmohanty11 can you please review the PR.

**Review by sidmohanty11 — CHANGES_REQUESTED** [review]
@imf-ali Awesome work, can you setup *lint-staged* with eslint and prettier? A husky hook that will make the changes for us will be a plus.

**Comment by imf-ali** [comment]
> @imf-ali Awesome work, can you setup _lint-staged_ with eslint and prettier? A husky hook that will make the changes for us will be a plus.

Configured _lint-staged_ for eslint and prettier.

**Review by sidmohanty11 — CHANGES_REQUESTED** [review]
@imf-ali Great! Can you please remove the test commits and I think this will be ready to get merged!

**Comment by imf-ali** [comment]
> @imf-ali Great! Can you please remove the test commits and I think this will be ready to get merged!

@sidmohanty11 Removed the commits related to testing.

**Review by sidmohanty11 — APPROVED** [review]
LGTM!

**Pull request merged**
