### PR TITLE
Fix: Quoting issues

### LINKED ISSUE #640: Bug: Message quoting issues
### Description:
Currently in EmbeddedChat there is an issue of quoting messages like quoting the messages recursively and quoting multiple messages at a time

### Steps to reproduce:
1. Open Embedded Chat
2. Quote multiple messages at a time
3. Also quote a quoted Message

### Expected behavior:
- [x] It should quote recursively
- [x] There should be multiple quoting of messages

### 1. No Recursive Quoting
image

### 2. No Multiple Quoting
[Screencast from 23-10-24 05:41:02 PM IST.webm](https://github.com/user-attachments/assets/b5f9a865-899c-4935-acc8-04e510118fb4)

### PR DESCRIPTION
**Pull request by devanshkansagra**
## Acceptance Criteria fulfillment

- [x] Recursively Quoting of messages
- [x] Multiple quoting of messages

Fixes #640 

## Video/Screenshots
[Screencast from 04-11-24 10:14:00 PM IST.webm](https://github.com/user-attachments/assets/3b9ef13b-e3dd-4b4d-a873-7ca38ed90fac)

## PR Test Details

**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-641/ after approval.

### CODE REVIEW

**Comment by devanshkansagra** [comment]
Hey @Spiral-Memory, I have implemented recursive and multiple quoting in EmbeddedChat, can you please review it?

**Comment by devanshkansagra** [comment]
Let me know once you check the deployment of this pull request

**Comment by Spiral-Memory** [comment]
Sure @devanshkansagra

**Comment by devanshkansagra** [comment]
Ok

**Comment by devanshkansagra** [comment]
Hey @Spiral-Memory, could you please approve to test so that can come to know whether the changes I made in this pr gets deployed properly and we can prevent the situation before we faced and we had to revert the changes.

**Review by Spiral-Memory — APPROVED** [review]
Approving to test ! Review pending

**Comment by devanshkansagra** [comment]
Okay

**Comment by devanshkansagra** [comment]
@Spiral-Memory, it is again facing the same error in deployment like earlier, but I am also confused that it is working properly in my local development environment but it is failing in the production build

**Comment by Spiral-Memory** [comment]
But as far as i can see, build succeeded

**Comment by devanshkansagra** [comment]
yea build is succeded but when I checked the logs, it issues is in the build part only

**Comment by devanshkansagra** [comment]
image

**Comment by devanshkansagra** [comment]
the above image is the error

**Comment by devanshkansagra** [comment]
preview.mjs:401 TypeError: Cannot read properties of undefined (reading '0')
    at Attachment (180.a44f4e00.iframe.bundle.js:1:205154)
    at Ch (preview.mjs:401:1)
    at ck (preview.mjs:401:1)
    at bk (preview.mjs:401:1)
    at ak (preview.mjs:401:1)
    at Tj (preview.mjs:401:1)
    at Lj (preview.mjs:401:1)
    at preview.mjs:401:1
    at exports.unstable_runWithPriority (preview.mjs:401:1)
    at gg (preview.mjs:401:1)

**Comment by devanshkansagra** [comment]
the above is the console error

**Comment by devanshkansagra** [comment]
Hey @Spiral-Memory, can you please approve again to test, coz I have added some checks

**Review by Spiral-Memory — APPROVED** [review]
Approving to test ! Review pending

**Comment by devanshkansagra** [comment]
it is now working well

**Comment by devanshkansagra** [comment]
you can test is

**Comment by devanshkansagra** [comment]
Hey @Spiral-Memory, I have tested from my side, it is working well, you can also test and review the code and output

**Comment by Spiral-Memory** [comment]
@devanshkansagra Please resolve the conflicts

**Comment by devanshkansagra** [comment]
Hey @Spiral-Memory, can you review the pr and also approve to test after to check whether everything is well

**Review by Spiral-Memory — APPROVED** [review]

**Comment by devanshkansagra** [comment]
Hey @Spiral-Memory, you can test the deployment and suggest any changes

**Comment by Spiral-Memory** [comment]
I'll test / review it and let you know

**Comment by devanshkansagra** [comment]
Hey @Spiral-Memory, Currently do not review or merge it coz I found a bug due to which the thread messages are not sended properly. You can check the pr deployment

**Comment by devanshkansagra** [comment]
Hey @Spiral-Memory, I have found the fix regarding thread messages were not sent in case of quoting message. Now you can review and verify and test yourself and suggest me if there are any changes

**Comment by devanshkansagra** [comment]
Hey @Spiral-Memory, can you approve to test?

**Review by Spiral-Memory — APPROVED** [review]

**Review by Spiral-Memory — COMMENTED** [review]
Awesome work @devanshkansagra 
Happy contributing...

**Pull request merged**
