### PR TITLE
Add pin icon to pinned messages

### LINKED ISSUE #415: Pinned Messages are not marked with appropriate Icon
### Steps to reproduce:

1. Messages
2. Pin a message

### Expected behavior:
- (from Rocket Chat)
image

### Actual behavior:
- (current embedded chats UI)
image

### PR DESCRIPTION
**Pull request by Akshun-01**
# Add `Pin Icon` to pinned messages for clear distinction

## Acceptance Criteria fulfillment

- [x] Check for message's pinned state
- [x] Add the pin icon accordingly

Fixes #415 

## Video/Screenshots
image

### CODE REVIEW

**Comment by Akshun-01** [comment]
I was also changing the pinned message icon in the toolbox to distinguish if it's pinned or not.
image
(It is currently the same for both states)
But I think Zishan is working on it. @Spiral-Memory ?

Also, the padding and UI of pinned messages is being taken care of in another [issue](https://github.com/RocketChat/EmbeddedChat/issues/374), so I skipped those.

**Comment by Akshun-01** [comment]
@abhinavkrin, could you please review the changes and give any feedback or corrections to be made?

Thanks! ^^

**Comment by Spiral-Memory** [comment]
> I was also changing the pinned message icon in the toolbox to distinguish if it's pinned or not. image (It is currently the same for both states) But I think Zishan is working on it. @Spiral-Memory ?
> 
> Also, the padding and UI of pinned messages is being taken care of in another [issue](https://github.com/RocketChat/EmbeddedChat/issues/374), so I skipped those.

@Akshun-01 , Yes i akshun, i have already added pinned message icon in the toolbox to distinguish if it's pinned or not, there was other issues as well and i have fixed all such issues and linked a PR as well, but the issue you have created to add pinned icon for clear distinction in message is different issue and it looks good, I haven't addressed that. Good work.

**Comment by Spiral-Memory** [comment]
@Akshun-01 , I would like to add one thing, In my PR #413, i have added a pin-filled icon too, once it gets merged, it will be better that you can use that icon just like star-filled.

**Comment by Akshun-01** [comment]
> @Akshun-01 , I would like to add one thing, In my PR #413, i have added a pin-filled icon too, once it gets merged, it will be better that you can use that icon just like star-filled.

Originally in rocket chat it uses pin icon(not filled), so i used the same here too for design consistency. 
(U can refer to image in main issue).
But we can consider this too, depends on the maintainer.
Thanks for this! ^^

**Comment by Spiral-Memory** [comment]
> > @Akshun-01 , I would like to add one thing, In my PR #413, i have added a pin-filled icon too, once it gets merged, it will be better that you can use that icon just like star-filled.
> 
> Originally in rocket chat it uses pin icon(not filled), so i used the same here too for design consistency. 
> (U can refer to image in main issue).
> But we can consider this too, depends on the maintainer.
> Thanks for this! ^^

Yes, I know that, but there in rocket chat app, they have a dialog box with a title that clearly states the difference between pinned and unpinned messages. Here, we don't have that. So, the only thing to distinguish between them is by adding a filled icon.

**Comment by Spiral-Memory** [comment]
Yaa any of these are fine. Depends on maintainer

**Comment by Akshun-01** [comment]
@abhinavkrin, there is one more feature related to this that can be implemented.

### In RocketChat we have a tooltip for both pinned and starred marked messages.
image
image

I am thinking of implementing this. 
But wanted to confirm whether we need this feature or not. Could you please confirm?
Thanks!

**Comment by abhinavkrin** [comment]
Hey. This could be implemented. Do take care of the cases:
1. where a message is both pinned and starred. 
2. The presence/absence of avatar for the message.

**Comment by Akshun-01** [comment]
## Added tootlip to icons : 
- Working great for the icons on the header 
image
image

### But there is some issue with the ones on the sequential messages

Changing z-index is not working and I think it is being cut off due to the parent container size restriction. 
image

- Translating it makes it look weird as it is not directly above the icon and I am trying not to change the Tooltip component for this. 

If anyone has any idea for this, please I would love to know about it.
Thanks! ^^

**Comment by Akshun-01** [comment]
Hey @Spiral-Memory, can you help me with this one, if you have some idea. 
thanks! ^^

**Comment by Spiral-Memory** [comment]
Sure, Can you share the complete screenshot. So i could understand the issue

**Comment by Akshun-01** [comment]
https://github.com/RocketChat/EmbeddedChat/assets/93793691/94a6f7e8-b0d3-485f-a23f-e307bbae5d95

As you can see in the above video, the `pinned message tooltip` is working fine on header messages but in sequential messages, it is overflowing and being cut out due to the screen size issue. In contrast, the original Rocket chat app has a higher z-index and can be seen easily. 

- Also changing the z-index is not helping here.
- Translating its position to the right makes it look weird, as the pointing part of the tooltip gets shifted, and I am trying not to change the tooltip component.

**Comment by Spiral-Memory** [comment]
Ahh, got it. See @Akshun-01 , I won't work like that. The website runs on Storybook, and the sidebar is a part of Storybook, where you can't use z-index. The sidebar is not a part of the website; you can only work with the allotted space. Since there is very little padding between the chat body and the corners, it is happening like that. However, in the Rocket Chat application, the sidebar is a part of the page. Do one thing: close the Storybook sidebar and then see; you will understand the issue better. To fix this, we could use padding, but I am not sure whether that would be a good approach. Send me a screenshot after closing the Storybook sidebar, and then we will see what can be done.

**Comment by Spiral-Memory** [comment]
I believe you can choose either of these approaches: show a smaller message as a tooltip that can fit in the given space, or keep the icons on the right side of the message. Both of these approaches will work. It might not match exactly with Rocket Chat, but the feature can be implemented in this way. Please proceed with that, share the images here, and let the maintainer have a look.

**Comment by Akshun-01** [comment]
Here is what it looks like after closing the sidebar
image

**Comment by Spiral-Memory** [comment]
> Here is what it looks like after closing the sidebar image

Yeah, so you've understood the issue, right? It is related to the space allocated to the site. The page has been designed to integrate into small spaces with only the chat body and no sidebar. Therefore, you have to adjust within the provided space itself. You can follow the suggestions I have provided; those will work. Adding padding to the entire page will also work, but that wouldn't be the correct solution.

**Comment by Akshun-01** [comment]
> I believe you can choose either of these approaches: show a smaller message as a tooltip that can fit in the given space, or keep the icons on the right side of the message. Both of these approaches will work. It might not match exactly with Rocket Chat, but the feature can be implemented in this way. Please proceed with that, share the images here, and let the maintainer have a look.

- Yeah, I was also thinking about shortening the message to `pinned` and `starred` instead of what it is now.
- I don't think adding it to the right side would be good UX-wise, as most of the time users would miss it, especially for long messages, it being too in the right. That's only my opinion tho.
image

**Comment by Akshun-01** [comment]
> > Here is what it looks like after closing the sidebar image
> 
> Yeah, so you've understood the issue, right? It is related to the space allocated to the site. The page has been designed to integrate into small spaces with only the chat body and no sidebar. Therefore, you have to adjust within the provided space itself. You can follow the suggestions I have provided; those will work. Adding padding to the entire page will also work, but that wouldn't be the correct solution.

Yeahh got it! Thanks for your insights! 
And yes increasing the padding of the page would defeat the purpose of fitting in small spaces itself. So, I wouldn't be doing that.

**Comment by Spiral-Memory** [comment]
> > I believe you can choose either of these approaches: show a smaller message as a tooltip that can fit in the given space, or keep the icons on the right side of the message. Both of these approaches will work. It might not match exactly with Rocket Chat, but the feature can be implemented in this way. Please proceed with that, share the images here, and let the maintainer have a look.
> 
> * Yeah, I was also thinking about shortening the message to `pinned` and `starred` instead of what it is now.
> * I don't think adding it to the right side would be good UX-wise, as most of the time users would miss it, especially for long messages, it being too in the right. That's only my opinion tho.
>   image

Yes, correct. So, whichever solution you feel is better, you can continue with that. Both approaches are a matter of choice. Let's go with the smaller message then.

**Comment by Akshun-01** [comment]
@abhinavkrin what are your thoughts on this?

**Comment by Akshun-01** [comment]
Hey, @abhinavkrin 
I have shortened the tooltip messages to fit in the required space. 
Could you please review the changes?

- This is the current status of the issue.

https://github.com/RocketChat/EmbeddedChat/assets/93793691/ff3128a6-f3ef-4015-9e98-53610e9c6841

**Comment by Akshun-01** [comment]
Let's wait for maintainers to review?

**Comment by Akshun-01** [comment]
@sidmohanty11 resolved conflicts, ready for review!

**Review by sidmohanty11 — APPROVED** [review]

**Pull request merged**
