### PR TITLE
Create .gitpod.yml

### PR DESCRIPTION
**Pull request by itsmanojthapa**
# this will start app automatically in gitpod

### CODE REVIEW

**Comment by sidmohanty11** [comment]
@itsmanojthapa Thanks for this!! We really need to gitpod-ize EmbeddedChat soon! However, I had an approach in mind:

EmbeddedChat requires:
- An RC instance
- Playground app

So, we need a way to gitpod-ize it in such a way that,
- it spins up a dockerized RC app
- use that RC app's host URL to instantiate EC playground app

I'm open to suggestions, let me know what you think

**Comment by itsmanojthapa** [comment]
@sidmohanty11 yes sure

**Comment by sidmohanty11** [comment]
@itsmanojthapa yes two servers:
- one dockerized RocketChat server
- one EmbeddedChat dev server (`npm run dev`)

**Comment by itsmanojthapa** [comment]
#182

**Pull request closed without merging**
