### PR TITLE
Fix for the positions of ChatHeader and Message Box : #134

### LINKED ISSUE #134: Fix the positions of ChatHeader and Message Box
### Description:
In the case of long messages, while scrolling down, the chat header becomes hidden, and while scrolling up message input box becomes hidden. Also we get two scroll bars, one for the message list component, other for complete window. Also there is scroll bar for going left and right in the window.

### Expected behavior:

- [ ] We should just have one scroll bar for scrolling the messages. 
- [ ] Chat header and message formatting box should be fixed.  
- [ ] There should be no scroll left to right or vice-versa.

### Actual behavior:
[screen-capture (1).webm](https://user-images.githubusercontent.com/42451210/219379676-54932336-5822-4cf8-a2b4-7cf6d43c0048.webm)

### PR DESCRIPTION
**Pull request by RahulNavneeth**
# Brief Title
Fixed the position of ChatBody by changing the width unit.

## Acceptance Criteria fulfillment

- [x] Task 1
- [x] Task 2
- [x] Task 3

Fixes #134 ( Fix for the positions of ChatHeader and Message Box )

### CODE REVIEW

**Comment by imf-ali** [comment]
Hey @RahulNavneeth can you attach a screen recording or screen shot.

**Comment by RahulNavneeth** [comment]
@imf-ali Here you go

https://user-images.githubusercontent.com/50259284/219857835-bc408b64-0cb4-4601-af88-a505f758172f.mp4

**Review by imf-ali — CHANGES_REQUESTED** [review]
I ran your code in local, we can still see some bug when we scroll, the header part is cut and also we have two scrollbar at the right.

image

**Review by imf-ali — CHANGES_REQUESTED** [review]
One more thing, when we scroll to the top, the Chat input box touches the bottom screen, both the header and Chat input box should be fixed.

image

**Comment by RahulNavneeth** [comment]
Right! That would be a easy fix but I am apparently stuck in 'api failed to fetch'(Both for google and Manual login) error and can't login.
any workarounds?
Thanks : )

**Comment by imf-ali** [comment]
Please ping your issue in the channel, there others can help you out as well. This is new feature and @VipinDevelops has worked on this.

**Comment by RahulNavneeth** [comment]
@imf-ali please review the pull request. Thanks 😄

**Pull request closed without merging**
