### PR TITLE
Fix: Sidebar starred messages fetched by api to include thread messages.

### LINKED ISSUE #668: Bug: Thread messages which are starred are not being showed up in the sidebar
### Description:
If a message is in thread and it is starred, then it is not shown in the sidebar. It only appears when we open the thread not by default. This defeats the purpose of starred messages.
### Steps to reproduce:

1. Write a message in thread.
2. Star that message.
3. Get out of that thread, and check sidebar. It should not be visible there.

### Expected behavior:
Any message that is starred should be seen in the sidebar by default.

### Actual behavior:

https://github.com/user-attachments/assets/ee1d5fb1-0caf-4ac7-b87f-a7a78c6ff598

### PR DESCRIPTION
**Pull request by Barrylimarti**
# Brief Title
Make thread starred messages appear in the sidebar.

## Acceptance Criteria fulfillment

- [ ] Fetch the response from getStarredMessages api instead of filtering it from the messages.
- [ ] Show it in the sidebar menu without breaking other functionalities.

Fixes #668

## Video/Screenshots

https://github.com/user-attachments/assets/a1e5642d-b4b5-425e-adfa-07c90203af9b

Realtime updation

https://github.com/user-attachments/assets/0c493e2a-2691-42b3-a2f1-ef760ee5b324

## PR Test Details

**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-669 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

### CODE REVIEW

**Review by Spiral-Memory — APPROVED** [review]
Testing deployment

**Comment by Spiral-Memory** [comment]
image

It is disturbing the fixed width of the sidebar, look into it

**Comment by Spiral-Memory** [comment]
I think this issue was introduced by another PR. Still, if possible, please work on it and ensure that the side panel has a fixed width, the same as when there is no content in it. I also noticed that this is happening in other side panels as well.

Merging this PR..

**Comment by Barrylimarti** [comment]
> I think this issue was introduced by another PR. Still, if possible, please work on it and ensure that the side panel has a fixed width, the same as when there is no content in it. I also noticed that this is happening in other side panels as well.
> 
> Merging this PR..

Alright, will look into that.

**Pull request merged**
