### PR TITLE
Fix issue: #350

### LINKED ISSUE #350: Add Menu-name when hovered over message menu-item
As an EmbeddedChat developer

**I need to**: Implement a feature of displaying message menu-item when hovered over the menu item. Just like in Rocket.Chat app.

**So That**: When hovered over the message menu-item, the name appears

**Acceptance Criteria**

- [X] Implement a feature of displaying message menu-item when hovered over the menu item.

[options.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/da2f1545-1d86-471c-a7ae-243fd8e4d19d)

### PR DESCRIPTION
**Pull request by devanshkansagra**
Fixes #350

### Implementation:

Imported the `Tooltip` component (`Tooltip.js`) in `MessageToolbox.js`.

A part of code
```
<Tooltip text="Edit" position="top">
  <ActionButton
    ghost={!isEditing}
    color={isEditing ? 'secondary' : 'default'}
    size="small"
    icon="edit"
    onClick={() => handleEditMessage(message)}
  />
</Tooltip>
```

## Output
[Screencast from 25-12-23 01:22:29 AM IST.webm](https://github.com/RocketChat/EmbeddedChat/assets/125076549/a4f7fb7b-6121-46bd-97c6-e4ffb0fd0ddc)

### CODE REVIEW

**Review by sidmohanty11 — APPROVED** [review]
Thanks @devanshkansagra ! LGTM

**Comment by devanshkansagra** [comment]
Hey @sidmohanty11,  are there any tasks or any changes to be made in this issue? If there are tasks to be done then I would be happy to contribute to this project.

**Comment by devanshkansagra** [comment]
Hey, @sidmohanty11 by mistake I pushed the commit for issue #369 to this branch. Could you Please help me to overcome from this mistake, or any changes I have to do in the commit history?

**Comment by devanshkansagra** [comment]
Due to merge of commit of issue #369 (by mistake) I am closing this PR and creating same new pr

**Pull request closed without merging**
