### PR TITLE
NEW: react to message

### LINKED ISSUE #34: Support for message reactions
As an EmbedChat developer

**I need to**: Create functionality to react to any message

**So That**: UX of users increases significantly

**Acceptance Criteria**

- [ ] API integration to send reactions
- [ ] List all reactions and count of reactions under the message
- [ ] Clicking on the reaction again should un-react the message

### PR DESCRIPTION
**Pull request by sidmohanty11**
# React to message

## Acceptance Criteria fulfillment

- [x] React to a message
- [x] Emoji + Counter under the message UI
- [x] handle un react to message

Fixes #34

### CODE REVIEW

**Comment by RonLek** [comment]
@sidmohanty11 a video demonstrating this would be helpful.

**Comment by sidmohanty11** [comment]
@RonLek done


https://user-images.githubusercontent.com/73601258/187639359-fb7a75f8-b6d1-47a0-ac50-058be5fe41c2.mp4

**Comment by RonLek** [comment]
@sidmohanty11 did the bug we discussed the other day get resolved by storing the username within cookies?

**Comment by sidmohanty11** [comment]
@RonLek yup, we are storing it but in local storage similar to avatar_url, here:
```javascript
const useUserStore = create((set) => ({
  ....
  username: localStorage.getItem('rc_uname') || '',
  ...
)}
```

**Comment by RonLek** [comment]
@sidmohanty11 could you please resolve conflicts on this one?

**Comment by sidmohanty11** [comment]
@RonLek done!

**Review by RonLek — APPROVED** [review]

**Pull request merged**
