### PR TITLE
feat: UiKit Modal Support

### LINKED ISSUE #474: Implement UIKit Modal Support in EmbeddedChat
To further enhance user interaction and engagement within this embedded environment, there's a need to integrate UIKit modals. UIKit modals are interactive dialogs that can display a wide range of content, including forms, information, confirmations, and more, directly within the chat interface.

#### Objective:
The primary goal is to implement UIKit Modal support in EmbeddedChat. This implementation should ensure that UIKit modals render correctly within the chat environment and that user actions on these modals are processed accurately. This feature is crucial for enabling a more interactive and engaging user experience, as it allows for complex interactions to be handled directly within the chat interface.

#### Key Requirements:
1. **UIKit Modal Rendering**: Enable the rendering of UIKit modals within EmbeddedChat.
2. **Action Processing**: Ensure that any actions taken within a UIKit modal (e.g., button clicks, form submissions) are correctly captured and communicated back to the Rocket.Chat server for processing. This may involve API calls or other mechanisms to handle user interactions.

### PR DESCRIPTION
**Pull request by Spiral-Memory**
# Brief Title
Implemented UIKit Modal Rendering to enable the rendering of UIKit modals within EmbeddedChat.

## Fulfillment of Acceptance Criteria

- [x] Added overflow menu in UiKitModal.
- [x] Integrated StaticSelect component in UiKitModal.
- [x] Incorporated MultiStaticSelect component in UiKitModal.
- [x] Added MessageGenericPreview component.
- [x] Implemented previewBlock without fuselage.
- [x] added multiple param support 

Fixes #474

## Video/Screenshots

https://github.com/RocketChat/EmbeddedChat/assets/78961432/08d5d20a-7ab8-4d99-956f-c17249e0810b

### CODE REVIEW

**Comment by Spiral-Memory** [comment]
Hey @abhinavkrin , I have successfully implemented the UIKitModal with all the required components mentioned in the TODO in the code, without using the fuselage. Additionally, I have addressed some minor issues and styling related to it. The UIKitModal is rendering properly in all the cases I have tested. To conduct testing, I used the Notion app due to its many different modals and properties.

However, I haven't implemented the task 2 of this issue, which involves capturing events and sending them to Rocket Chat for processing. I am unable to understand how the actions are being dispatched. I need your help with this or suggest collaboration with other contributor to complete it. Even after checking the Rocket Chat app and live chat app, I'm still not sure how the actions are sent. Right now, the rendering task of this issue is completed.

**Review by sidmohanty11 — COMMENTED** [review]
Hey @Spiral-Memory awesome work! Just wanted to know is it safe to merge this? As this will enable us the UI right? Just not the functionalities? We can take up the functionalities on the subsequent PR.

**Comment by Spiral-Memory** [comment]
Yes @sidmohanty11 , It's completely safe to merge it, as far as i have tested, it doesn't introduce any bugs.. also if I find any, i will immediately fix it, so no worries. Yes only functionality has to be implemented now.

**Comment by sidmohanty11** [comment]
Awesome!

**Review by sidmohanty11 — APPROVED** [review]

**Pull request merged**
