### PR TITLE
Typing-text fixed

### LINKED ISSUE #365: Typing-Text issue
### Description:
The Typing text which is displayed when the user is typing, is being displayed even when the message is sent and no user is typing. It only disappears when clicked out of the text area. 

### Steps to reproduce:

1. Open storybook
2. Click on `ChatInput` text-area.
3. Type a message. And Send it.
4. The `<user> is typing...` message still appears until clicked outside somewhere.

### Expected behavior:

The typing message should not be displayed when message is sent. Only displayed when user is typing.

### Actual behavior:
[type.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/9e330bf9-7d14-4108-b6b8-178b176f082b)

**Update**: The Issue was only when 'Enter' key is pressed, not when message is sent through the Send Button in text area.

### PR DESCRIPTION
**Pull request by umangutkarsh**
# Brief Title
This PR fixes the issue mentioned in #365 .

## Acceptance Criteria fulfillment

- [X] Issue fixed
- [X] Checks passed

Fixes #365 

## Video/Screenshots
[type2.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/4d95ae12-0b42-4fb2-bfeb-b2da3ad7784e)

### CODE REVIEW

**Review by sidmohanty11 — COMMENTED** [review]
Hey @umangutkarsh ! Awesome! Just a quick question do you think the correct UX will be not showing that "the current user" is typing and just show it when others are typing? Just curious.

**Comment by devanshkansagra** [comment]
Hey @umangutkarsh, Due to some issues in https://chat.avitechlab.com/, I was unable to log in, it says privacy error, so I decided to setup rocket chat server locally but when I log in it displays CORS error, can you tell me how to overcome this error.

image

**Comment by umangutkarsh** [comment]
> Hey @umangutkarsh, Due to some issues in https://chat.avitechlab.com/, I was unable to log in, it says privacy error, so I decided to setup rocket chat server locally but when I log in it displays CORS error, can you tell me how to overcome this error.
> 
> image

I am able to access the hosted server now, yesterday I wasn't able to. 
Also I haven't setup the server locally, I used gitpod to setup RocketChat server, and it was working fine.
Can you try with gitpod maybe?

**Comment by umangutkarsh** [comment]
> Hey @umangutkarsh ! Awesome! Just a quick question do you think the correct UX will be not showing that "the current user" is typing and just show it when others are typing? Just curious.

Yup, but this was the default behavior earlier, I just adjusted the code to stop displaying the message of "<user> is typing..." when the user has sent the message.

Should I work on the issue you mentioned?

**Comment by sidmohanty11** [comment]
@umangutkarsh yup, that will be awesome!

**Review by sidmohanty11 — APPROVED** [review]

**Comment by devanshkansagra** [comment]
Hey @umangutkarsh, I have setup the server on gitpod and I am running this Embedded Chat project locally, but still getting the same CORS error, my server url is https://3000-rocketchat-rocketchat-6vh7kt451c1.ws-us107.gitpod.io. I have inserted this url in the host section 
image
and still giving me the same error.
image
Please help me to resolve this error :pray:

**Comment by Kamlesh72** [comment]
Try this.
https://www.youtube.com/watch?v=l-6OIvolqyE

**Comment by devanshkansagra** [comment]
> Try this. https://www.youtube.com/watch?v=l-6OIvolqyE

Thank you so much! Now I am relieved

**Comment by umangutkarsh** [comment]
> Hey @umangutkarsh, I have setup the server on gitpod and I am running this Embedded Chat project locally, but still getting the same CORS error, my server url is https://3000-rocketchat-rocketchat-6vh7kt451c1.ws-us107.gitpod.io. I have inserted this url in the host section image
> 
> and still giving me the same error.
> 
> image Please help me to resolve this error 🙏

Hey @devanshkansagra . Sorry for responding late. Didn't see this yesterday.
Hope you have resolved your issue.

**Comment by devanshkansagra** [comment]
yes it is resolved

**Pull request merged**
