### PR TITLE
Feat/#274 replace message components with custom components

### LINKED ISSUE #274: Replace fuselage's Message, MessageReaction, and MessageDivider component with our own component
1. Replace the fuselage's Message, MessageReaction, and MessageDivider component with our own components
2. The components should implement the defined theming system

### PR DESCRIPTION
**Pull request by umangutkarsh**
# Brief Title

Replaced the components `Message, MessageReactions, MessageDivider` imported in `/packages/react/src/components/SearchMessage/SearchMessage.js` with custom Message.js, MessageReactions.js and MessageDivider.js files.

## Acceptance Criteria fulfillment

- [X] Removed `@rocket.chat/fuselage` import in `SearchMessage.js`
- [X] Implemented custom components.
- [X] Imported custom components.
- 

Fixes #274

### CODE REVIEW

**Comment by abhinavkrin** [comment]
Hi @umangutkarsh,

I've noticed the search message feature isn't working as expected after the recent changes in [PR #278](https://github.com/RocketChat/EmbeddedChat/pull/278). Could you please take a look?

Also, it would be great if we could test out the functionalities before finalizing PRs. This helps make the review process more efficient.

Thanks for your understanding and assistance!

**Comment by umangutkarsh** [comment]
> I've noticed the search message feature isn't working as expected after the recent changes in this PR. Could you please take a look?
> 
> Also, it would be great if we could test out the functionalities before finalizing PRs. This helps make the review process more efficient.
> 
> Thanks for your understanding and assistance!

Hi @abhinavkrin, I'll look into it. Also how should I test it? Can't view the components in storybook.

**Comment by umangutkarsh** [comment]
> Hi @umangutkarsh,
> 
> I've noticed the search message feature isn't working as expected after the recent changes in this PR. Could you please take a look?
> 
> Also, it would be great if we could test out the functionalities before finalizing PRs. This helps make the review process more efficient.
> 
> Thanks for your understanding and assistance!

Hi @abhinavkrin, I've made some changes. I need to test those. Would be helpful if you guide me. 
Thanks for this.

**Comment by abhinavkrin** [comment]
Please follow the readme files to set up project locally. One good practice is to use the project and play with it in order to understand how it works and what it provides.

**Comment by umangutkarsh** [comment]
> Please follow the readme files to set up project locally. One good practice is to use the project and play with it in order to understand how it works and what it provides.

I've set the project locally. And there is no issues with the storybook, and auth dev environment. But I was not able to setup the api dev-environment.

**Comment by abhinavkrin** [comment]
Api and Auth are not required to be running to test EmbeddedChat. They are build and installed in EmbeddedChat as dependencies.

**Pull request merged**
