### PR TITLE
Feature : Login System Enhancement

### LINKED ISSUE #103: [TODO] Support all OAuth providers
As an EmbedChat developer

**I need to**: Make sure that EmbeddedChat supports all OAuth providers

**So That**: There is no immediate limitations and everyone can access their RC instance without any data loss.

**Acceptance Criteria**

- [ ] Nextcloud OAuth
- [ ] Facebook OAuth
- [ ] Gitlab OAuth
- [ ] GitHub OAuth
- [ ] WordPress OAuth
- [x] Normal Input based sign-in (Username/Password) - highest priority

Docs: https://docs.rocket.chat/use-rocket.chat/rocket.chat-workspace-administration/settings/oauth

### **Sign in with Google should change with - "JOIN"**
image

### **Join should open up a modal with all the providers the user has given in props**
image

For Implementation, refer this PR: #12

### PR DESCRIPTION
**Pull request by VipinDevelops**
Details:
This PR focuses on adding a new feature to the existing login system, allowing users to sign in using either their username or email and password. The new feature also includes normal input-based sign-in, with username/password being the highest priority.

The acceptance criteria fulfillment includes:
Task 1: Implementation of the ability to sign-in using either username or email
Task 2: Is TOTP compatible 
Task 3: User-friendly interface for the login process

fix #103 
- [x]  Normal Input based sign-in (Username/Password) - highest priority

Video:  

[Screencast from 2023-02-05 14-45-12.webm](https://user-images.githubusercontent.com/99081689/216811024-064d8527-ddf8-4ba6-89ae-5d95e12a6f9c.webm)

### CODE REVIEW

**Comment by VipinDevelops** [comment]
Hey sidharth this PR is almost ready just need some styling 

I asked krishna and other community members to help me out 

You can go through the logic and let me know if any changes required 

Thank you

**Comment by VipinDevelops** [comment]
Hey, @sidmohanty11 just wanted to let you know that I finished working on the login system with username and password functionality. @SKB231  was a great help, he assisted me in creating the modal and styling it. 
Please review the PR 
Do let me know if any changes are required.
Thank you.

**Comment by sidmohanty11** [comment]
@VipinDevelops This is amazing!!!! Thanks!!!

**Review by sidmohanty11 — APPROVED** [review]

**Comment by VipinDevelops** [comment]
> @VipinDevelops This is amazing!!!! Thanks!!!


Thanks for @sidmohanty11  we are now working on other auth systems as well

**Pull request merged**
