### PR TITLE
fix/User avatar not visible after pinning a message. #466

### PR DESCRIPTION
**Pull request by Sayan4444**
# Brief Title
User avatar not visible after pinning a message

## Acceptance Criteria fulfillment

Fixes # (issue)
#466  #465 

## Video/Screenshots
Screenshot 2024-02-17 113010

### CODE REVIEW

**Comment by Spiral-Memory** [comment]
Hey @Sayan4444, Good work!
I have a few small suggestion, it would be great if you do that as well. 

1. Have a small gap between the vertical line and rest of the content.
2. Reduce the gap between avatar emoji and the username, keep a little gap.
3. Keep some gap between the actual message and (username+avatar) vertically.

**Comment by Spiral-Memory** [comment]
Yes looks better bro 😃, Awesome 💯

**Comment by Sayan4444** [comment]
image

**Comment by Sayan4444** [comment]
image
Sorry by mistake I forced pushed a commit which made it to close the PR 
This is the new PR 
https://github.com/RocketChat/EmbeddedChat/pull/484

**Pull request closed without merging**
