### PR TITLE
changes made to readme.md and added steps for

### PR DESCRIPTION
**Pull request by coderboy-yash**
# Brief Title

## Acceptance Criteria fulfillment

- [x] link added to the Wiki & FAQs page for videos,
- [x] Link to Roots and internals of EmbeddedChat wiki added.
- [x] Cool screenshots added.
- [x] headerColor, toastBarPosition are added to the props list with description.
- [x] mock image for embedded chat added. 
- [x] installation issue resolved for windows user.

Fixes # (issue)

### CODE REVIEW

**Comment by coderboy-yash** [comment]
I have updated the readme as you said and also added steps for setting up the project for a Windows user which was mention in issue #210 
if you have any issues with this pull request, message me so I can solve it.

**Review by sidmohanty11 — CHANGES_REQUESTED** [review]
@coderboy-yash Awesome, thanks a lot!

Can you please add a good mockup image for embeddedchat? For example, take a look at: https://github.com/RocketChat/RC4Community. Also, please update the PR description

**Comment by coderboy-yash** [comment]
thanks for the appreciation, yes I can make the changes.

**Comment by coderboy-yash** [comment]
I have done the changes in the pr you told please review it.

**Review by sidmohanty11 — APPROVED** [review]
Thanks @coderboy-yash ! LGTM, we can change the photo later - we can tag something like "in-appchat for any web app"

**Pull request merged**
