### PR TITLE
Change starred and pinned message windows to sidebar

### LINKED ISSUE #498: Change starred and pinned message windows to sidebar
As an EmbeddedChat developer

**I need to**:
Change starred and pinned message windows to sidebar

**So That**:
They match with other options in the chat room (threads, search, mentions, members, and room information), which all show information in sidebars. RC also displays these options in sidebars. 

Currently, it's weird to have starred and pinned messages expand to full window while other options show as sidebar. Having this inconsistent UI could confuse users.

**Acceptance Criteria**

- [x] Change starred messages window to sidebar
- [x] Change pinned messages window to sidebar

### PR DESCRIPTION
**Pull request by JeffreytheCoder**
## Acceptance Criteria fulfillment

- [x] Change pinned messages window to sidebar
- [x] Change starred messages window to sidebar

Fixes #498 

## Video/Screenshots

sidebar

### CODE REVIEW

**Review by sidmohanty11 — APPROVED** [review]
Thanks @JeffreytheCoder !

**Comment by sidmohanty11** [comment]
@abhinavkrin can you also please take a look?

**Comment by JeffreytheCoder** [comment]
@sidmohanty11 @abhinavkrin Is this PR good to merge?

**Comment by sidmohanty11** [comment]
Yes lets merge this @JeffreytheCoder ! Thanks

**Pull request merged**
