### PR TITLE
Added Functionality to Customise theme using Props

### PR DESCRIPTION
**Pull request by Ayyanaruto**
# Functionality to Theme your Chat using Props

## Changes Done

- [ ] Added two Props called primaryColor and secondaryColor in RCComponent
- [ ] primaryColor is responsible for backgroundColors of  all components
- [ ] secondaryColor is responsible for changing text color of input ,messages or any other text related components
- [ ]  The background of Chatheader and ChatInput will be lighter if body background is Dark or dark if background-color is  light they will be darker which gives a good contrast to our app
- [ ] Also  changed  some styling added box-shadow, border-radius to ChatHeader and more

## Video/Screenshots

<h2> Some Examples</h2>

<h3 align="middle"> Light Colors</h3>
<p float="left">
  
   
  

</p>
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
<h3 align="middle"> Dark Colors</h3>
<p float="left">
  
   

  
</p>
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
<h3 align="middle"> This  is the  Default Theme</h3>

Default

### CODE REVIEW

**Comment by sidmohanty11** [comment]
This is amazing @Ayyanaruto ! It would be great if you could attend the weekly catchup to discuss more on this

**Comment by Ayyanaruto** [comment]
Sure, It will be notified on #embedded chat channel on Rocket chat,right?

**Comment by sidmohanty11** [comment]
Yup, sure will notify there too if you want. I usually notify inside official channels,

- For EC2023 - https://open.rocket.chat/channel/idea-embedded-chat-2023

**Comment by Ayyanaruto** [comment]
Thanks @sidmohanty11 I joined the above mentioned channel, I will check the meetings from there

**Pull request closed without merging**
