### PR TITLE
fixed  markdown rendering in report message

### LINKED ISSUE #610: Markdown rendering issue in report message
### Description:

While reporting messages, markdown rendering doesn't works fine

### Steps to reproduce:

1. Select any message
2. report the message

### Expected behavior:

The text while reporting the message should be rendered properly.

### Actual behavior:

https://github.com/user-attachments/assets/ec1e7e4e-ddb6-4f98-8077-f881f475ad58

### PR DESCRIPTION
**Pull request by smritidoneria**
# Brief Title
In report message, text shown is appropiate and readable.
## Acceptance Criteria fulfillment

- [x] Changed the title text visibility in report message

Fixes  #610

## Video/Screenshots

https://github.com/user-attachments/assets/de1bab68-3f3b-4466-9587-26c90865322f

### CODE REVIEW

**Review by Spiral-Memory — APPROVED** [review]

**Comment by smritidoneria** [comment]
Both the implementation looks good, we can go @sidmohanty11 approach

**Comment by Spiral-Memory** [comment]
Hey @smritidoneria 
Is this ready for review ?

**Comment by Spiral-Memory** [comment]
Hey @smritidoneria 
Is this ready for review ?

**Comment by smritidoneria** [comment]
yes, it is ready for review @Spiral-Memory .

**Review by Spiral-Memory — APPROVED** [review]

**Pull request merged**
