### PR TITLE
Fix/#334 source image fix

### LINKED ISSUE #334: Source Image of members in MemberList not displayed.
### Description:

The images of members are not displayed in the member-list. The reason for this is that the hard-coded value of the host url should be modified.

### Steps to reproduce:

1. Click on 3 dots in chat-bar above.
2. Click on Members

### Expected behavior:

The source images should be displayed.

### Actual behavior:

member

### PR DESCRIPTION
**Pull request by umangutkarsh**
# Brief Title
Fixed Source Image not displayed of members.

## Acceptance Criteria fulfillment

- [X] Replaced hard-coded value of host

Fixes #334 

## Video/Screenshots
member

### CODE REVIEW

**Comment by umangutkarsh** [comment]
> Hey @umangutkarsh Thanks for bringing out the issue. However your solution wont work. I would suggest constructing the source using the host passed in the props as base URL. The host could be accessed using
> 
> ```
> const { ECOptions } = useRCContext();
> const { host } = ECOptions;
> ```

Hey @abhinavkrin . I've modified the code. Can you please take out your time and review it?.
Btw just curious, why won't my solution work as it worked in the PR #289 which resolved the issue #265 .

Thanks.

**Review by abhinavkrin — APPROVED** [review]
Thanks @umangutkarsh for the fix.

**Comment by abhinavkrin** [comment]
> > Hey @umangutkarsh Thanks for bringing out the issue. However your solution wont work. I would suggest constructing the source using the host passed in the props as base URL. The host could be accessed using
> > ```
> > const { ECOptions } = useRCContext();
> > const { host } = ECOptions;
> > ```
> 
> Hey @abhinavkrin . I've modified the code. Can you please take out your time and review it?. img
> 
> Btw just curious, why won't my solution work as it worked in the PR #289 which resolved the issue #265 .
> 
> Thanks.

@umangutkarsh, regarding your question, the environment variable setup is exclusive to Storybook and isn't included when we bundle our application with Rollup. This means those specific ENV variables aren't available in the Rollup bundle. Also, for the EmbeddedChat component, we pass the 'host' as a prop, which varies based on the developer's environment and the Rocket.Chat server used. This approach ensures our component is adaptable for different development scenarios.

**Comment by umangutkarsh** [comment]
> > > Hey @umangutkarsh Thanks for bringing out the issue. However your solution wont work. I would suggest constructing the source using the host passed in the props as base URL. The host could be accessed using
> > > ```
> > > const { ECOptions } = useRCContext();
> > > const { host } = ECOptions;
> > > ```
> > 
> > 
> > Hey @abhinavkrin . I've modified the code. Can you please take out your time and review it?. img
> > Btw just curious, why won't my solution work as it worked in the PR #289 which resolved the issue #265 .
> > Thanks.
> 
> @umangutkarsh, regarding your question, the environment variable setup is exclusive to Storybook and isn't included when we bundle our application with Rollup. This means those specific ENV variables aren't available in the Rollup bundle. Also, for the EmbeddedChat component, we pass the 'host' as a prop, which varies based on the developer's environment and the Rocket.Chat server used. This approach ensures our component is adaptable for different development scenarios.

Okk. Makes sense,

**Pull request merged**
