### PR TITLE
Added a feature to copy messages and copy link in message tool box

### LINKED ISSUE #709: Feat: Add copy message and copy link feature
As an EmbeddedChat developer I want to implement  a feature to copy a message in EmbeddedChat. so that users can copy a message and send that to other channels. Also Rocket chat provides us an option to copy the message and copy the link would be nice to have similar options in embedded chat.

**Acceptance Criteria**

- [x] Implement a copy message feature 
- [x] Implement copy link feature

### Actual behaviour
No copy message button available
image

### PR DESCRIPTION
**Pull request by devanshkansagra**
## Acceptance Criteria fulfillment

- [x] Implemented copying a message feature
- [x] Implemented copying link of the message

Fixes #709

## Video/Screenshots
[Screencast from 22-12-24 02:04:35 PM IST.webm](https://github.com/user-attachments/assets/595646cc-0a5c-4c8d-a3c9-fe15281b57ba)

## PR Test Details

**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-710 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

### CODE REVIEW

**Review by Spiral-Memory — APPROVED** [review]

**Comment by Spiral-Memory** [comment]
Hi @devanshkansagra 

I noticed that you’ve made changes to the theme editor for consistency as well. Could you attach a video demonstrating that it works fine?  

I’m unable to see those changes in the deployed version. Not sure if we deployed the latest `layout_editor` in the PR.

**Review by Spiral-Memory — APPROVED** [review]

**Comment by devanshkansagra** [comment]
Hey @Spiral-Memory, thanks for pointing it out, just regarding that only I want to ask you something. I have watched your layout_editor video and in that I observed that you added that theme json in EmbeddedChat rc-app, and in that I have also uploaded my theme json generarted from layout_editor, but it does not reflected any changes. also I observed you have added client-id and client-secret so can you tell how did you get those?

**Comment by Spiral-Memory** [comment]
> Hey @Spiral-Memory, thanks for pointing it out, just regarding that only I want to ask you something. I have watched your layout_editor video and in that I observed that you added that theme json in EmbeddedChat rc-app, and in that I have also uploaded my theme json generarted from layout_editor, but it does not reflected any changes. also I observed you have added client-id and client-secret so can you tell how did you get those?

After uploading your JSON and saving it, you need to check in Storybook where the remote settings are applied. There is a prop, `isRemote` (or something similar), that needs to be set to `true` to view it. There’s already a story that displays the remote settings.  

As for the client ID and secret, I’m not sure which one you’re referring to.

**Comment by Spiral-Memory** [comment]
For now, you can remove all the changes from layout_editor in this PR, so i can merge this, maybe make it consistent in some other pr

**Comment by devanshkansagra** [comment]
Okay then

**Comment by devanshkansagra** [comment]
Hey can you re-run this workflow https://github.com/RocketChat/EmbeddedChat/actions/runs/12453015921, I think the pages-deployment workflow is not triggered or might got skipped and due to that the changes might not reflected.

do it after any build-pr or deploy-pr workflow is completed

**Comment by devanshkansagra** [comment]
ok do not re-run it changes are visible

**Comment by devanshkansagra** [comment]
image
I found that here it is causing

**Pull request merged**
