### PR TITLE
Feat/#274 replace message components with custom components in SearchMessage.js

### LINKED ISSUE #274: Replace fuselage's Message, MessageReaction, and MessageDivider component with our own component
1. Replace the fuselage's Message, MessageReaction, and MessageDivider component with our own components
2. The components should implement the defined theming system

### PR DESCRIPTION
**Pull request by umangutkarsh**
## Brief Title
Replaced Message, MessageDivider, MessageReactions _fuselage_ components with custom components

## Acceptance Criteria fulfillment

- [X] Import custom components
- [X] Use custom components in `SearchMessage.js`

Fixes #274 (Closed Issue - _Replace fuselage's Message, MessageReaction, and MessageDivider component with our own component_)

## Video/Screenshots
search-message

### CODE REVIEW

**Comment by umangutkarsh** [comment]
Hey @abhinavkrin . Sorry to bother. But I've created a new pull request for the issue #274 (Already closed). 

The problem I was having is now resolved. Thank you for everything,
Can you please look into it and provide your feedback? It will be really helpful for me if anything else is required. 
I've also provided the working screenshot of the search-message feature.

Thanks for your time.

**Comment by umangutkarsh** [comment]
I'll resolve the conflicts once you check the PR.

**Comment by umangutkarsh** [comment]
Hey @abhinavkrin . If there is any kind of misunderstanding I think it should be communicated. I am aware that I did some mistakes which were because I was not able to test the changes in the storybook. But that is resolved now. Thanks.

Kindly respond to this, or maybe we can sort out any misunderstanding over a call. Please respond so that I at least know what went wrong. Please just hear my side of the story also if there is any problem.

Hoping to get a response whenever you are free.

**Comment by abhinavkrin** [comment]
Hello @umangutkarsh,

My apologies for the delayed response. I've been tied up with several priorities recently. For immediate assistance, feel free to reach out on our community channel. Our collaborative environment ensures there's always someone available with the expertise to guide you, even if I'm momentarily unavailable.

Regarding your PR, I plan to review it shortly. In the meantime, could you please address the existing conflicts? This proactive step would expedite the process once I'm ready to merge your valuable contributions.

**Comment by umangutkarsh** [comment]
> Hello @umangutkarsh,
> 
> My apologies for the delayed response. I've been tied up with several priorities recently. For immediate assistance, feel free to reach out on our community channel. Our collaborative environment ensures there's always someone available with the expertise to guide you, even if I'm momentarily unavailable.
> 
> Regarding your PR, I plan to review it shortly. In the meantime, could you please address the existing conflicts? This proactive step would expedite the process once I'm ready to merge your valuable contributions.

Thanks for the response. This means alot. I understand that you've been tied up with some work. No issues regarding that. 
But since I wasn't getting any response since last week I concluded that maybe it was me who did something wrong.
No worries. Please take your time. 


I'll resolve the conflicts asap. 
And thanks again.

**Comment by abhinavkrin** [comment]
Hey @umangutkarsh,

Thanks a lot for your PR! Really appreciate the effort and time you've put into this. Just wanted to give you a heads up that we've actually resolved this issue with a recent update.

But seriously, it's great to see your involvement and eagerness to contribute. Your input is always valuable and we're excited to see more of your work in the future. Keep it up!
ss

**Pull request closed without merging**
