### PR TITLE
Fixed issue: #350

### LINKED ISSUE #350: Add Menu-name when hovered over message menu-item
As an EmbeddedChat developer

**I need to**: Implement a feature of displaying message menu-item when hovered over the menu item. Just like in Rocket.Chat app.

**So That**: When hovered over the message menu-item, the name appears

**Acceptance Criteria**

- [X] Implement a feature of displaying message menu-item when hovered over the menu item.

[options.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/da2f1545-1d86-471c-a7ae-243fd8e4d19d)

### PR DESCRIPTION
**Pull request by devanshkansagra**
Fixes #350

### Implementation:

Imported the `Tooltip` component (`Tooltip.js`) in `MessageToolbox.js`.

A part of code
```
<Tooltip text="Edit" position="top">
  <ActionButton
    ghost={!isEditing}
    color={isEditing ? 'secondary' : 'default'}
    size="small"
    icon="edit"
    onClick={() => handleEditMessage(message)}
  />
</Tooltip>
```

## Output
[Screencast from 25-12-23 01:22:29 AM IST.webm](https://github.com/RocketChat/EmbeddedChat/assets/125076549/a4f7fb7b-6121-46bd-97c6-e4ffb0fd0ddc)

### CODE REVIEW

**Comment by devanshkansagra** [comment]
This is the same new PR which was closed before. All the changes are same nothing is changed. If there are any changes to be made the tell me I would happy to contribute to this project

**Review by sidmohanty11 — CHANGES_REQUESTED** [review]
Hey @devanshkansagra thanks for the PR, seems like you've added an extra `package-lock` file and `yarn-lock` changes but I don't see any dependency changes so this should not be the case

**Comment by devanshkansagra** [comment]
Actually I setup the server on gitpod so due to that those files were added

**Comment by abhinavkrin** [comment]
> @sidmohanty11, Actually I setup the server on gitpod so due to that those files were added

Hey @devanshkansagra , you should remove package-lock.json. Run `yarn`. Commit and push if any changes occur in the yarn.lock file

**Comment by devanshkansagra** [comment]
Ok, Noted

**Pull request closed without merging**
