### PR TITLE
modified root folder's README file for better explanation

### PR DESCRIPTION
**Pull request by Dev-Code24**
README.MD file updated 

gave a better explanation for a better understanding

## Video/Screenshots

image

### CODE REVIEW

**Review by sidmohanty11 — CHANGES_REQUESTED** [review]
Hey @Dev-Code24 thanks a lot for your PR! Can we change it to something like -> `# at the root folder - embeddedchat`?

Also, I had some other Readme changes in mind, please feel free to add them and modify the README into a cool one if you are willing to.

- Addition of a link to the Wiki/FAQs page for videos,
- Link to Roots of EmbeddedChat wiki with a link to [this](https://github.com/RocketChat/EmbeddedChat/wiki/How-to-create-your-own-component-library%3F) that will help people get a better sense of understanding of its internals.
- A cool screenshot maybe! [You can refer this](https://github.com/RocketChat/RC4Community)
- Add `headerColor`, `toastBarPosition` to the props list and update its description, [refer this](https://github.com/RocketChat/EmbeddedChat/blob/f272e2cab37a769dc15c8806439ab80bb0513c91/src/index.js#L22)

Feel free to add more to this list if you think something else needs to be changed. This will be a significant contribution!

**Comment by Dev-Code24** [comment]
> Hey @Dev-Code24 thanks a lot for your PR! Can we change it to something like -> `# at the root folder - embeddedchat`?
> 
> Also, I had some other Readme changes in mind, please feel free to add them and modify the README into a cool one if you are willing to.
> 
> * Addition of a link to the Wiki/FAQs page for videos,
> * Link to Roots of EmbeddedChat wiki with a link to [this](https://github.com/RocketChat/EmbeddedChat/wiki/How-to-create-your-own-component-library%3F) that will help people get a better sense of understanding of its internals.
> * A cool screenshot maybe! [You can refer this](https://github.com/RocketChat/RC4Community)
> * Add `headerColor`, `toastBarPosition` to the props list and update its description, [refer this](https://github.com/RocketChat/EmbeddedChat/blob/f272e2cab37a769dc15c8806439ab80bb0513c91/src/index.js#L22)
> 
> Feel free to add more to this list if you think something else needs to be changed. This will be a significant contribution!

yeah sure I will make these changes

**Comment by Dev-Code24** [comment]
@sidmohanty11 
I have made the changes as per request, but I was unable to put a cool screenshot

**Review by sidmohanty11 — CHANGES_REQUESTED** [review]
@Dev-Code24 can you please revert to your first commit.

**Comment by sidmohanty11** [comment]
> Hey @Dev-Code24 thanks a lot for your PR! Can we change it to something like -> `# at the root folder - embeddedchat`?
> 
> Also, I had some other Readme changes in mind, please feel free to add them and modify the README into a cool one if you are willing to.
> 
> * Addition of a link to the Wiki/FAQs page for videos,
> * Link to Roots of EmbeddedChat wiki with a link to [this](https://github.com/RocketChat/EmbeddedChat/wiki/How-to-create-your-own-component-library%3F) that will help people get a better sense of understanding of its internals.
> * A cool screenshot maybe! [You can refer this](https://github.com/RocketChat/RC4Community)
> * Add `headerColor`, `toastBarPosition` to the props list and update its description, [refer this](https://github.com/RocketChat/EmbeddedChat/blob/f272e2cab37a769dc15c8806439ab80bb0513c91/src/index.js#L22)
> 
> Feel free to add more to this list if you think something else needs to be changed. This will be a significant contribution!

@Dev-Code24  I am making this a separate issue to take up! Just make your initial changes with making the comment more descriptive -> by adding something like -> `at the root folder - EmbeddedChat`

**Review by sidmohanty11 — CHANGES_REQUESTED** [review]
@Dev-Code24 rebase it please to the initial commit

**Comment by sidmohanty11** [comment]
Git rebase: https://www.simplilearn.com/what-is-git-rebase-command-article

**Comment by Dev-Code24** [comment]
> Git rebase: https://www.simplilearn.com/what-is-git-rebase-command-article

oh, so you meant this,
Thank you for sharing the link.

**Comment by Dev-Code24** [comment]
> @Dev-Code24 rebase it please to the initial commit

sorry for the trouble but can you please tell me what I need to do here, I can't understand how to rebase my final commit with the initial commit as in all the tuts I saw about the git rebase, they all are showing that "git rebase" is done with 2 branches: master/main and a feature branch.

**Comment by sidmohanty11** [comment]
@Dev-Code24 you could try [git reset](https://www.techtarget.com/searchitoperations/answer/How-to-roll-back-Git-code-to-a-previous-commit) it should be a bit easier I think

**Comment by Dev-Code24** [comment]
> @Dev-Code24 you could try [git reset](https://www.techtarget.com/searchitoperations/answer/How-to-roll-back-Git-code-to-a-previous-commit) it should be a bit easier I think
I did git reset. Can you please help what should I do next? Like should I commit to something new or do a push?

**Comment by sidmohanty11** [comment]
@Dev-Code24 you can do a force push

**Comment by Dev-Code24** [comment]
> @Dev-Code24 you can do a force push

The following is shown to me and I cannot see any changes

Screenshot 2022-12-25 at 20 01 16

**Comment by sidmohanty11** [comment]
Hey @Dev-Code24 , I'm so sorry for the late response. I am actually very busy with exams right now. Please feel free to open a new PR for this! Thanks !

**Comment by Dev-Code24** [comment]
Hey @sidmohanty11 no problem, but I guess you said that you were going to do this, so shall I do it or you will do it?

**Comment by sidmohanty11** [comment]
> Hey @Dev-Code24 thanks a lot for your PR! Can we change it to something like -> `# at the root folder - embeddedchat`?
> 
> Also, I had some other Readme changes in mind, please feel free to add them and modify the README into a cool one if you are willing to.
> 
> * Addition of a link to the Wiki/FAQs page for videos,
> * Link to Roots of EmbeddedChat wiki with a link to [this](https://github.com/RocketChat/EmbeddedChat/wiki/How-to-create-your-own-component-library%3F) that will help people get a better sense of understanding of its internals.
> * A cool screenshot maybe! [You can refer this](https://github.com/RocketChat/RC4Community)
> * Add `headerColor`, `toastBarPosition` to the props list and update its description, [refer this](https://github.com/RocketChat/EmbeddedChat/blob/f272e2cab37a769dc15c8806439ab80bb0513c91/src/index.js#L22)
> 
> Feel free to add more to this list if you think something else needs to be changed. This will be a significant contribution!

I deviated here actually, your PR was to specify the folder accurately but I introduced so many complications here. You can just make the initial PR with your changes (at root folder - EmbeddedChat)

**Comment by Dev-Code24** [comment]
@sidmohanty11 
Ok, I will do that.
One more thing I wanted to ask was can you actually help me by guiding me on how the mentors or the organizations select students/contributors for GSOC.
I am a 2nd-year student at DTU, Delhi, and wanted help from someone regarding GSOC.

**Comment by sidmohanty11** [comment]
@Dev-Code24 sure, you can ask your doubts in DM (RC or LinkedIN)

**Comment by Dev-Code24** [comment]
> @Dev-Code24 sure, you can ask your doubts in DM (RC or LinkedIN)

Yeah sure.
(https://www.linkedin.com/in/rajeev-lochan-14812922b)

**Pull request closed without merging**
