### PR TITLE
Fix: Fixed basic design issues, added changeable pin icons, and added a dynamic header that can show the section in which the user is located.

### LINKED ISSUE #412: Minor design fixes needed, and a dynamic header required when users viewing starred or pinned messages.
### Description:

This particular issue discusses various UI bugs that need correction to ensure a smooth user experience and better accessibility. Additionally, I would like to address the addition of a dynamic header when users are viewing their starred or pinned messages. Currently, there is no way of knowing in which section the user is

### Steps to reproduce:

1. Open Embedded Chat App using yarn storybook command and check all the issue mentioned.

### Actual behavior: (Issues)

**Major Issues**

Issue 1: The Emoji Picker always opens in the center of the page, whether attempting to send a message or react to one. Both buttons are located in different position but still emoji picker opens in center of the page, which is inconvenient for users, requiring them to navigate to the center just to send an emoji—a suboptimal user experience.

Screenshot from 2024-01-19 16-59-44

Issue 2: The user is not informed about whether they are in the starred or pinned message section after moving into it as there is no header or anything mentioning that. Also, to go back, A blue button with an unaligned icon is present with text "Go back", resulting in an inconsistent and unappealing design.

Screenshot from 2024-01-19 17-05-44

Issue 3: The pin icon doesn't change when pinned or unpinned, making it challenging for the user to identify which messages are pinned and can be unpinned.

Screenshot from 2024-01-19 17-05-34

**Minor Issues** 

Issue 4: There is no separation between the left border and the pinned message notification text.

Screenshot from 2024-01-19 17-05-24

Issue 5: There is inadequate padding in the 'Report Message' or 'Delete Message' modals between elements.

Screenshot from 2024-01-19 17-07-29

Issue 6: There is an unequal gap in message metrics.

Screenshot from 2024-01-19 17-13-53

### Expected behavior:

**Major Issues** 

Issue 1: The emoji picker must open in the same location where it was triggered.

Issue 2: When entering the pinned or starred message section, a dynamic header should display the current section for user orientation. Along with that, a design consistent button must be there to exit the section.

Issue 3: When pinning a message, the pin icon should change to indicate that the message has been pinned and can now be unpinned if needed.

**Minor Issues**

Issue 4: Ensure proper separation between the left border and the pinned message notification text.

Issue 5: Maintain proper spacing between various elements in the 'Report Message' or 'Delete Message' sections.

Issue 6: Ensure equal spacing between all buttons and icons in message metrics for a better UI.

### PR DESCRIPTION
**Pull request by Spiral-Memory**
This PR solves many minor UI issues as well as some major things that must be addressed to improve overall user experience, especially the icon change when pinned, and the dynamic header to inform the user in which section he is in.

## Acceptance Criteria fulfillment

Your list appears to have some minor grammar and punctuation issues. Here's a revised version:

- [x] Fixed emoji picker positions so that it opens at the point where it is triggered.
- [x] Added a dynamic header, so that whenever the user navigates to either a starred message or pinned message, it shows the section name in that.
- [x] Added a pin-filled icon so that the pin can change when the message is pinned and is ready for unpinning, and vice versa.
- [x] Fixed all other spacing issues as mentioned in issue 410.

Fixes #412 

Note: Having a look at the issue is necessary to understand the problems this PR addresses.

## Video/Screenshots

Screenshot from 2024-01-19 18-57-16

Screenshot from 2024-01-19 18-57-23

Screenshot from 2024-01-19 19-00-47

Screenshot from 2024-01-19 19-00-00

Screenshot from 2024-01-19 18-52-59

Screenshot from 2024-01-19 18-53-18

Screenshot from 2024-01-19 18-49-50

Screenshot from 2024-01-19 19-02-07

### CODE REVIEW

**Comment by Spiral-Memory** [comment]
Recently added another commit to slightly change the search input style from this:

Screenshot from 2024-02-01 16-14-14

to this:

Screenshot from 2024-02-01 16-13-35

**Comment by abhinavkrin** [comment]
Hey @Spiral-Memory Thanks a lot for the awesome changes. I have a little confusion
The back button in threads message is location in the header but the back button appears in chat box for other cases.
I was thinking of implementing  a uniform behavior for this. Can we add the back button to header in all the cases?

**Comment by Spiral-Memory** [comment]
Sure, @abhinavkrin sir, I will make the suggested changes as a separate PR. I have attempted it, and it will necessitate some additional adjustments. I'll request you to merge this one since it already includes numerous changes. The modification you suggested will be implemented in a separate PR. If you prefer it in this PR, feel free to let me know, but I believe keeping it separate will simplify the review process for this PR."

**Comment by abhinavkrin** [comment]
Cool @Spiral-Memory Could you resolve the merge conflicts?

**Comment by Spiral-Memory** [comment]
Yes @abhinavkrin sir done

**Review by abhinavkrin — APPROVED** [review]
LGTM! Great Work.

**Pull request merged**
