### PR TITLE
Gitpod setup

### LINKED ISSUE #178: Gitpod-ize EmbeddedChat
As an EmbeddedChat developer

**I need to**: So, we need a way to gitpod-ize it in such a way that,
- it spins up a dockerized RC app
- use that RC app's host URL to instantiate EC playground app

**So That**: I can start Embedded chat in gitpod

**Acceptance Criteria**

- [ ] one dockerized RocketChat server
- [ ] one EmbeddedChat dev server

### PR DESCRIPTION
**Pull request by imf-ali**
As an EmbeddedChat developer

**I need to**: So, we need a way to gitpod-ize it in such a way that,
- it spins up a dockerized RC app
- use that RC app's host URL to instantiate EC playground app

**So That**: I can start Embedded chat in gitpod

**Acceptance Criteria**

- [x] one dockerized RocketChat server
- [x] one EmbeddedChat dev server 

This is the video link. The video was bit a longer.
https://drive.google.com/file/d/1cnYfKA3Chlicbo8kqUEjMUyyu6YsuSdX/view?usp=sharing 

Fix #178

### CODE REVIEW

**Comment by imf-ali** [comment]
Hey @sidmohanty11 can you please have a look?

**Comment by sidmohanty11** [comment]
@imf-ali this is great!!! It would be great if you could add a Gitpod logo button (in the README) for one-click setup.

Also if you can, please provide a screen recording of how this should look like and I will add this PR to `wiki` page mentioning the steps.

Again, awesome work!

**Comment by imf-ali** [comment]
> @imf-ali this is great!!! It would be great if you could add a Gitpod logo button (in the README) for one-click setup.
> 
> Also if you can, please provide a screen recording of how this should look like and I will add this PR to `wiki` page mentioning the steps.
> 
> Again, awesome work!

@sidmohanty11, I added a screen recording, but its size was more than 10 mb, so I gave a g-drive link.

**Review by sidmohanty11 — APPROVED** [review]
@imf-ali this is great work! Kudos! 

This enhances DevX 100x! Cheers!

**Comment by sidmohanty11** [comment]
@imf-ali please add a gitpod button in README and this is good to go!

**Pull request merged**
