### PR TITLE
Fix overflow of long messages

### PR DESCRIPTION
**Pull request by sahilsekr42**
# Fix overflow of long messages
I've tried to solve Overflown Message View issue
## Acceptance Criteria fulfillment

- [x] added word break property

Fixes # 45

## Video/Screenshots
Screenshot from 2023-01-10 09-50-06

### CODE REVIEW

**Comment by sidmohanty11** [comment]
Hey @sahilsekr42 , thanks a lot for this PR! This solves a very big issue as in conferences message box(EmbeddedChat in this case) have compressed width.

**Review by sidmohanty11 — APPROVED** [review]
LGTM!

**Comment by sidmohanty11** [comment]
@sahilsekr42 feel free to join [#embeddedchat](https://open.rocket.chat/channel/embeddedchat) channel in open.rocket.chat we'll love to have you there.

Also, if you're preparing for GSOC23 join #gsoc2023 channel and introduce yourself there and add yourself to the GSoC Contributors Leaderboard -> gsoc.rocket.chat

**Comment by sahilsekr42** [comment]
Thank you for quick response ,  seeing the pr merged is great feeling . Also for gsoc23 leaderboard could you elaborate on the process . Is there a gsoc.rocket.chat server also I couldn't find #gsoc2023 channel but there is a team of channels .Shall I introduce there??

**Comment by sahilsekr42** [comment]
> @sahilsekr42 feel free to join [#embeddedchat](https://open.rocket.chat/channel/embeddedchat) channel in open.rocket.chat we'll love to have you there.
> 
> Also, if you're preparing for GSOC23 join #gsoc2023 channel and introduce yourself there and add yourself to the GSoC Contributors Leaderboard -> gsoc.rocket.chat

@sidmohanty11 Hope to contribute more . Are there some other issues or enhancements that nobody is working on ? Sorry to bother...

**Comment by sidmohanty11** [comment]
@sahilsekr42

GSoC contributor leaderboard -> https://gsoc.rocket.chat/
#gsoc2023 channel -> https://open.rocket.chat/channel/gsoc2023
#landing-your-first-pr channel -> https://open.rocket.chat/channel/landing-your-first-pr

We would love to see your contributions in future! Feel free to join #embeddedchat channel for more discussions and start playing around a bit with Embeddedchat, you'll definitely find something that's in your interest.

**Pull request merged**
