### PR TITLE
Fix: prevent chat window resize on long links

### LINKED ISSUE #92: Size getting large on sending long links
### Steps to reproduce:

1. Send a long link in the chat

### Expected behavior:

The chat window should maintain its constant width

### Actual behavior:

On sending longer links, the chat window gets enlarged

image

### PR DESCRIPTION
**Pull request by haresahani**
# Fix Message Body Word Wrapping and Overflow Handling

 - Ensure long links break properly in the message body without overflowing.
 - Apply word-wrap and overflow-wrap to the message body and anchor tags.
 - Ensure the styles are consistent across light and dark modes.
 - Validate that text and links in the message body wrap normally.

Fixes #92

### CODE REVIEW

**Comment by devanshkansagra** [comment]
Hey @haresahani, There are lots of unwanted additions in package.json in every monorepo package, can you please discard the unnecessary ones

**Review by devanshkansagra — CHANGES_REQUESTED** [review]
if the file as a dependency in every package is unnecessary then kindly remove all of those
these ones:
"@embeddedchat/api": "file:"
"@embeddedchat/auth": "file:"
"docs": "file:",
"@embeddedchat/htmlembed": "file:",
"@embeddedchat/rc-app": "file:"
"@embeddedchat/react-native": "file:",
"@embeddedchat/ui-elements": "file:",
"@embeddedchat/ui-kit": "file:",

**Comment by Spiral-Memory** [comment]
@haresahani 

With 1 lakh lines of changes, something seems off. Please review this PR carefully.

**Review by Spiral-Memory — CHANGES_REQUESTED** [review]
@haresahani
With 1 lakh lines of changes, something seems off. Please revise this PR carefully. Please respond to it, or i'll have to close this PR to avoid confusion for other collaboraors.

**Pull request closed without merging**
