### PR TITLE
[IMPROVE] Attachment window

### PR DESCRIPTION
**Pull request by RahulNavneeth**
# Description
This pull request builds the ability to add descriptions and change name to attachments directly into the chat window, making it easier to understand the context with one another.

## Changes Made
The following changes have been made to implement this feature:

1. A modal window for modifying the file name and description.

BEFORE:

https://user-images.githubusercontent.com/50259284/222400440-50c53e59-0702-4fae-9bfd-84c3995f13b8.mp4

AFTER:

https://user-images.githubusercontent.com/50259284/222400520-46a0167a-73e4-48a0-a7d0-ec6480f28fc6.mp4

### CODE REVIEW

**Comment by RahulNavneeth** [comment]
hey @sidmohanty11  , Can you kindly review this pull request. Thanks 😄.

**Comment by sidmohanty11** [comment]
@RahulNavneeth looks great, PTAL at the merge conflicts

**Comment by RahulNavneeth** [comment]
> @RahulNavneeth looks great, PTAL at the merge conflicts

Done sir 👍

**Comment by RahulNavneeth** [comment]
@sidmohanty11 Can you kindly review the changes made, Thanks 😄

**Comment by RahulNavneeth** [comment]
Hi @sidmohanty11  Can you kindly review the changes made, Thanks 😄

**Review by sidmohanty11 — APPROVED** [review]
Awesome @RahulNavneeth !

**Pull request merged**
