### PR TITLE
Fixed the issue of appearance of pinned messages when pinning a message with emojis

### LINKED ISSUE #374: Unexpected appearance of the pinned messages while pinning emojis.
### Description:

When a message containing a emoji is pinned the appearance is not as expected.

### Expected behavior:

Screenshot (42)

### Actual behavior:

Screenshot (44)

### PR DESCRIPTION
**Pull request by devanshkansagra**
# Fixed the Emoji appearance issue

Fixes #374

Apart of code
```js
<Box>
       {attachment?.text ? (
        <MessageEmoji body={attachment?.text} />
      ) : (
        attachment?.txt
      )}
</Box>
```

## Video/Screenshots
Screenshot from 2024-01-10 23-32-32

### CODE REVIEW

**Comment by devanshkansagra** [comment]
Hey, @Yashraj7890, Please notify me if any tasks to be done specific to this issue, I will be happy to contribute.

**Review by devanshkansagra — COMMENTED** [review]
Hey, Can you please review my changes?

**Comment by devanshkansagra** [comment]
image

I had also put some ```inline css``` to the pinned message component so that things look proper

# Code Changes (Added these lines)
```jsx
import RCContext from '../../context/RCInstance';
import { Avatar } from '../Avatar';
```

```jsx
<Box style={{paddingLeft: '0.3rem'}}>
        <Avatar
          url={getUserAvatarUrl(attachment?.author_name)}
          alt="avatar"
          size={attachment?.text.t ? '1.2em' : '1.8em'}
        /> <>{attachment?.author_name}</>
      </Box><br/>
```

**Comment by devanshkansagra** [comment]
Hey @sidmohanty11, Can you please review my changes in this PR? Also please notify me if any changes to be made

**Comment by devanshkansagra** [comment]
Hey @sidmohanty11, I want to follow up on this PR - any feedback, information or any suggestions needed for this?

**Comment by devanshkansagra** [comment]
Hey @sidmohanty11 & @abhinavkrin, can  anyone of you please review my pull request? so that I can follow up.

**Comment by abhinavkrin** [comment]
Hey could you provide some information about the current behaviour. It would help me review this PR.

**Comment by devanshkansagra** [comment]
Yeah, This pull request is about fixing the unexpected appearence of pinned messages when it is pinned with emojis. The issue was: when the message with emoji was pinned, it displays the emoji text instead of emoji. I had made changes in Pinned Attachment component(the code is above). This code fixes this issue and display the pinned message with emoji.

And I had made some design changes through inline css so that it looks like the way it is in rocket chat server

**Comment by devanshkansagra** [comment]
> image
> 
> I had also put some `inline css` to the pinned message component so that things look proper
> 
> # Code Changes (Added these lines)
> ```js
> import RCContext from '../../context/RCInstance';
> import { Avatar } from '../Avatar';
> ```
> 
> ```js
> const { RCInstance } = useContext(RCContext);
>     const getUserAvatarUrl = (username) => {
>     const host = RCInstance.getHost();
>     const URL = `${host}/avatar/${username}`;
>     return URL;
> };
> ```
> 
> ```js
> <Box style={{paddingLeft: '0.3rem'}}>
>         <Avatar
>           url={getUserAvatarUrl(attachment?.author_name)}
>           alt="avatar"
>           size={attachment?.text.t ? '1.2em' : '1.8em'}
>         /> <>{attachment?.author_name}</>
>       </Box><br/>
> ```

These are the latest changes I have made

**Comment by devanshkansagra** [comment]
Hey @abhinavkrin, any suggestions?

**Comment by devanshkansagra** [comment]
Hey @abhinavkrin, is everything okay in code??

**Comment by devanshkansagra** [comment]
Hello there !

**Comment by devanshkansagra** [comment]
Hey @abhinavkrin, Any suggestions regarding this changes and current behaviour? Is everything okay or not?

Please tell me.

**Comment by devanshkansagra** [comment]
@sidmohanty11, Any suggestions?

**Comment by Akshun-01** [comment]
Hey, I think it's the : 
- margin between username and text ( It should be a bit less) 
- Padding between (username+text) component and the rest of the elements ( It is originally much greater which makes it look uniform and organised)> 
Hope this helps! ^^

**Comment by devanshkansagra** [comment]
Ok, will do that

**Comment by devanshkansagra** [comment]
> Hey @devanshkansagra , Great work!! I think it's the :
> 
> * margin between username and text ( It should be a bit less)
> * Padding between (username+text) component and the rest of the elements ( It is originally much greater which makes it look uniform and organised)
> 
> Hope this helps! ^^

Did you mean avatar (user logo) + username??

**Comment by devanshkansagra** [comment]
image

Hello maintainers,
I had made these changes as per your requirement. Any suggestions regarding this?

**Comment by devanshkansagra** [comment]
image

I have changed the padding of the text message 
Can anyone please check if it is proper or not and review these changes

**Comment by devanshkansagra** [comment]
Can anyone review the changes I made?

**Comment by devanshkansagra** [comment]
Hello Everyone, Any changes to be made??

**Comment by devanshkansagra** [comment]
Hey @sidmohanty11 , @abhinavkrin, @Akshun-01, @Yashraj7890, Can anyone of you please review my changes and give suggestions regarding the code changes??

**Comment by Yashraj7890** [comment]
Hey @devanshkansagra the maintainers must be occupied please wait a bit more and your changes will be reviewed soon.

**Comment by devanshkansagra** [comment]
Yea, ok no problem

**Comment by devanshkansagra** [comment]
Hello maintainer, I am requesting you, Could you please please review my PR and give me suggestions so that I can further work on. And also sorry for continuously requesting for PR reviewal, I am a beginner and I just started contributing to the opensource. It would be happy and would encourage me to contribute further if you review it.

**Comment by devanshkansagra** [comment]
Hey @abhinavkrin, Do I create a new branch and push the code? Because there are some conflicts occured recently with this branch.

**Comment by devanshkansagra** [comment]
Hey @abhinavkrin, I am deleting this branch and closing this PR because there are some conflicts occured. So for that I had created a new branch and pushed the changes into that 

The new PR RAISED: https://github.com/RocketChat/EmbeddedChat/pull/448

**Pull request closed without merging**
